

render_file:
    pattern: render/*/*
    defaults:
        component: core\components\render\RenderComponent
        controller:  core\components\render\controllers\RenderController
        model:  core\components\render\models\RenderModel
        method: renderFile
        view: core\views\RenderHTMLView
        viewKey: render_file
        datasource: datasource1
        langFiles:
    listeners:
        - { 'event': 'entry_point', 'listener': 'core\components\render\eventlisteners\ConfigurationListener'}
        - { 'event': 'entry_point', 'listener': 'core\components\render\eventlisteners\LoadCachedPageListener', static: 'true'}
        - { 'event': 'request_start', 'listener': 'core\components\render\eventlisteners\LoadFileToRenderListener', static: 'true'}
        - { 'event': 'request_start', 'listener': 'core\components\render\eventlisteners\ConfigureLocaleStringsListener' }
        - { 'event': 'request_start', 'listener': 'core\components\locales\eventlisteners\LoadLocaleStringsListener' }
        - { 'event': 'render_complete', 'listener': 'core\components\render\eventlisteners\SaveCachedPageListener', static: 'true'}
    methods: [GET]
    

render_file_with_param:
    pattern: render/*/*/*
    defaults:
        component: core\components\render\RenderComponent
        controller:  core\components\render\controllers\RenderController
        model:  core\components\render\models\RenderModel
        method: renderFile
        view: core\views\RenderHTMLView
        viewKey: render_file
        datasource: datasource1
        langFiles:
    listeners:
        - { 'event': 'request_start', 'listener': 'core\components\render\eventlisteners\ConfigurationListener'}
        - { 'event': 'request_start', 'listener': 'core\components\render\eventlisteners\LoadCachedPageListener', static: 'true'}
        - { 'event': 'request_start', 'listener': 'core\components\render\eventlisteners\ConfigureLocaleStringsListener' }
        - { 'event': 'request_start', 'listener': 'core\components\locales\eventlisteners\LoadLocaleStringsListener' }
        #- { 'event': 'render_complete', 'listener': 'core\components\render\eventlisteners\SaveCachedPageListener', static: 'true'}

    methods: [GET]    
