
website_contactus_get:
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/contactus/views/subnav.php"
            "section3": "src/components/contactus/views/get.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
admin_contactus_list:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/contactus/views/admin/subnav.php"
            "section3": "src/components/contactus/views/admin/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
admin_contactus_view: 
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/contactus/views/admin/subnav.php"
            "section3": "src/components/contactus/views/admin/view.php"
            "section4": "src/themes/default/templates/sections/footer.php"           
    
admin_contactus_edit:   
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/contactus/views/admin/subnav.php"
            "section3": "src/components/contactus/views/admin/edit.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
            

    