

admin_ticker_request_token:
    pattern: admin/ticker/requesttoken/*/*
    methods: [GET]
    defaults:
        component: components\ticker\TickerComponent
        controller: components\ticker\controllers\TickerController
        model: components\ticker\models\TickerModel
        method: requestToken
        view: core\views\AJAXHTMLView
        viewKey: admin_ticker_request_token
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  