

admin_subcontractors_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/subcontractors/views/admin/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - subcontractorsAdmin
            - rootApp
    head:
        - @components/subcontractors/dist/bower_components/angular/angular.min.js
        - @components/subcontractors/dist/bower_components/jquery/dist/jquery.min.js
        - @components/subcontractors/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/subcontractors/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
    javascript:
        - @components/subcontractors/dist/js/subcontractors.concat.js
    css:
        - @components/subcontractors/includes/css/subcontractors.css
        
        
       
            
admin_subcontractors_edit:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/subcontractors/views/admin/edit.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - subcontractorsAdmin
            - rootApp
    head:
        - @components/subcontractors/dist/bower_components/angular/angular.min.js
        - @components/subcontractors/dist/bower_components/jquery/dist/jquery.min.js
        - @components/subcontractors/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/subcontractors/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
    javascript:
        - @components/subcontractors/dist/js/subcontractors.concat.js
    css:
        - @components/subcontractors/includes/css/subcontractors.css
        
        
        
    
admin_subcontractors_list_contacts:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/subcontractors/views/subnav.php"
            "section3": "src/components/subcontractors/views/contacts/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_subcontractors_edit_contact:   
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/subcontractors/views/subnav.php"
            "section3": "src/components/subcontractors/views/contacts/add.php"
            "section4": "src/themes/default/templates/sections/footer.php" 