admin_claims_initial_jobsheet:
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'event': 'request_start', 'listener': 'components\claims\listeners\LoadQueryParamsListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimModel', 'cacheKey': 'Params' }
        # build the form for Claim Location
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ClaimLocationModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'claimLocationForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
                - { dependency: Params, model: ClaimLocation }


admin_claims_edit_initial_jobsheet:
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\customers\models\CustomerTypeModel', 'cacheKey': 'CustomerTypes' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactVIPTypeModel', 'cacheKey': 'ContactVIPTypes' }
        - { 'event': 'request_start', 'listener': 'components\claims\listeners\LoadQueryParamsListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimModel', 'cacheKey': 'Params' }
        - { 'event': 'request_start', 'listener': 'components\inventory\listeners\ListEquipmentInitialJobsheetListener', 'datasource': 'datasource1', 'class': 'components\inventory\models\InventoryEquipmentModel', 'cacheKey': 'InventoryEquipment' }

        # build the form for Project Address
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\projects\form\ProjectBuilder'
            model: 'components\projects\models\ProjectAddressModel'
            cacheKey: 'ProjectAddressForm'
            formName: 'projectAddressForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
        # build the form for Claim Location
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ClaimLocationModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'claimLocationForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
                - { dependency: Params, model: ClaimLocation }
        # build the form for Contact
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\customers\form\CustomerBuilder'
            model: 'components\customers\models\CustomerModel'
            cacheKey: 'ContactForm'
            formName: 'contactForm'
            dependencies:
                - { dependency: CustomerTypes, key: customerTypes, value: CustomerTypes_id, text: type }
                - { dependency: Provinces, key: provinces, value: id, text: province }
                - { dependency: ContactVIPTypes, key: contactVIPTypes, value: ContactVIPTypes_id, text: type }

admin_claims_view_initial_jobsheet:
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\customers\models\CustomerTypeModel', 'cacheKey': 'CustomerTypes' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactVIPTypeModel', 'cacheKey': 'ContactVIPTypes' }
        - { 'event': 'request_start', 'listener': 'components\claims\listeners\LoadQueryParamsListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimModel', 'cacheKey': 'Params' }
        - { 'event': 'request_start', 'listener': 'components\inventory\listeners\ListEquipmentInitialJobsheetListener', 'datasource': 'datasource1', 'class': 'components\inventory\models\InventoryEquipmentModel', 'cacheKey': 'InventoryEquipment' }

        # build the form for Project Address
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\projects\form\ProjectBuilder'
            model: 'components\projects\models\ProjectAddressModel'
            cacheKey: 'ProjectAddressForm'
            formName: 'projectAddressForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
        # build the form for Claim Location
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ClaimLocationModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'claimLocationForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
                - { dependency: Params, model: ClaimLocation }
        # build the form for Contact
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\customers\form\CustomerBuilder'
            model: 'components\customers\models\CustomerModel'
            cacheKey: 'ContactForm'
            formName: 'contactForm'
            dependencies:
                - { dependency: CustomerTypes, key: customerTypes, value: CustomerTypes_id, text: type }
                - { dependency: Provinces, key: provinces, value: id, text: province }
                - { dependency: ContactVIPTypes, key: contactVIPTypes, value: ContactVIPTypes_id, text: type }



admin_claims_secondarysheets_get:
    listeners:
        - { 'cacheKey': 'AffectedAreaActions', 'class': 'components\claims\models\SecondarySheetModel', responseKey: AffectedAreaActions, listener: 'components\claims\listeners\LoadSecondarySheetQuestionsListener', 'event': 'request_start', 'datasource': 'datasource1'}
        - { 'cacheKey': 'SerializedAffectedAreaActions', 'dependency': AffectedAreaActions, 'class': 'components\claims\models\SecondarySheetModel', responseKey: SerializedAffectedAreaActions, listener: 'components\claims\listeners\SerializeSecondarySheetQuestionsListener', 'event': 'request_start', 'datasource': 'datasource1'}
                
        -
            event: 'request_end'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\SecondaryJobSheetBuilder'
            model: 'components\claims\models\SecondarySheetModel'
            cacheKey: 'SecondarySheetQuestions'
            formName: 'secondarySheet'
            dependencies:
                - { dependency: AffectedAreaActions, model: AffectedAreaActions }
    

admin_claims_list_claimlocation_photocounts:    
    listeners:
        - { 'cacheKey': 'LocationFiles', 'class': 'components\claims\models\ClaimModel', 'event': 'request_start', 'listener': 'components\claims\listeners\LoadFileCountsListener', 'datasource': 'datasource1' }


admin_claims_edit:   
    listeners:
        - { 'class': 'components\claims\models\ClaimDocumentModel', 'event': 'request_start', 'listener': 'components\claims\listeners\LoadDocumentCountsListener', 'datasource': 'datasource1' }
        - { 'event': 'request_start', 'listener': 'components\claims\listeners\LoadClaimByJobNumberListener', 'datasource': 'datasource1', cacheKey: Claim}
#        - { 'event': 'request_start', 'listener': 'components\claims\listeners\LoadClaimByJobNumberListener', 'datasource': 'datasource1', cacheKey: 'claimTest'}
        - { 'cacheKey': 'DocumentTypes', 'class': 'components\documents\models\DocumentTypeModel', 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'cacheKey': 'ClaimsLocations', 'class': 'components\claims\models\ClaimLocationModel', 'event': 'request_start', 'listener': 'components\claims\listeners\LoadClaimLocationsByClaimIdListener', 'datasource': 'datasource1' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactVIPTypeModel', 'cacheKey': 'ContactVIPTypes' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\customers\models\CustomerTypeModel', 'cacheKey': 'CustomerTypes' }

        -
            event: 'request_end'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\documents\form\DocumentBuilder'
            model: 'components\documents\models\DocumentTypeModel'
            cacheKey: 'DocumentUploadForm'
            formName: 'documentForm'
            dependencies:
                - { dependency: DocumentTypes, key: documentTypes, value: id, text: type }
                - { dependency: ClaimsLocations, key: claimLocations, value: id, text: unitNumber }
#                - { dependency: Claim, key: claimTest, value: id, text: phase }
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimBuilder'
            model: 'components\claims\models\ClaimModel'
            cacheKey: 'ClaimForm'
            formName: 'form'
            dependencies:
                - { dependency: Claim, model: Claim}
                - { dependency: ContactVIPTypes, key: contactVIPTypes, value: ContactVIPTypes_id, text: type }
                - { dependency: CustomerTypes, key: customerTypes, value: CustomerTypes_id, text: type }


admin_claims_cost_cards_edit:
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimPhaseModel', 'cacheKey': 'ClaimPhases' }


admin_claims_location_view:
    listeners:
        - { 'cacheKey': 'DocumentTypes', 'class': 'components\documents\models\DocumentTypeModel', 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'cacheKey': 'AreaTypes', 'class': 'components\scoping\models\AreaTypeModel', 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactVIPTypeModel', 'cacheKey': 'ContactVIPTypes' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\customers\models\CustomerTypeModel', 'cacheKey': 'CustomerTypes' }
        - { 'class': 'components\vehicles\models\VehicleModel', 'cacheKey': 'Vehicles', 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'class': 'components\inventory\models\WarehouseModel', 'cacheKey': 'WarehouseLocations', 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }

#        - { 'cacheKey': 'test', 'class': 'components\claims\models\ClaimLocationModel', 'event': 'request_start', 'listener': 'components\claims\listeners\LoadClaimLocationsByClaimIdListener', 'datasource': 'datasource1' }
#        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
#        - { 'event': 'request_start', 'listener': 'components\claims\listeners\LoadQueryParamsListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimModel', 'cacheKey': 'Params' }
        # build the form for Claim Location
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ClaimLocationModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'form'
            dependencies:
                - { dependency: AreaTypes, key: areaTypes, value: id, text: type }
                - { dependency: ContactVIPTypes, key: contactVIPTypes, value: ContactVIPTypes_id, text: type }
                - { dependency: CustomerTypes, key: customerTypes, value: CustomerTypes_id, text: type }

        -
            event: 'request_end'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\documents\form\DocumentBuilder'
            model: 'components\documents\models\DocumentTypeModel'
            cacheKey: 'DocumentUploadForm'
            formName: 'documentForm'
            dependencies:
                - { dependency: DocumentTypes, key: documentTypes, value: id, text: type }                
#                - { dependency: AreaTypes, key: areaTypes, value: id, text: title }
#                - { dependency: ClaimsLocations, key: claimLocations, value: id, text: unitNumber }
        -
            event: 'request_end'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\inventory\form\InventoryEquipmentTransferBuilder'
            model: 'components\inventory\models\InventoryEquipmentModel'
            cacheKey: 'TransferForm'
            formName: 'transferForm'
            dependencies:
                - { dependency: WarehouseLocations, key: warehouseLocations, value: id, text: name }
                - { dependency: Vehicles, key: vehicles, value: id, text: number }

admin_claims_home:        
    listeners:
        - { 'event': 'request_start', 'listener': 'core\components\widgets\eventlisteners\LoadSystemWidgetsListener', 'datasource': 'datasource1', 'cacheKey': 'SystemWidgets'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactVIPTypeModel', 'cacheKey': 'ContactVIPTypes' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\customers\models\CustomerTypeModel', 'cacheKey': 'CustomerTypes' }
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ClaimLocationModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'form'
            dependencies:
                - { dependency: ContactVIPTypes, key: contactVIPTypes, value: ContactVIPTypes_id, text: type }
                - { dependency: CustomerTypes, key: customerTypes, value: CustomerTypes_id, text: type }

                
admin_claims_cost_cards_edit:
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimPhaseModel', 'cacheKey': 'ClaimPhases' }
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\CostCardBuilder'
            model: 'components\accounting\models\CostCardModel'
            cacheKey: 'CostCardForm'
            formName: 'form'
            dependencies:
                - { dependency: ClaimPhases, key: claimPhases, value: id, text: title }

