## YAML Template.
---
claimsAddNewModal:
    path: 'src/components/claims/ng/views/claimsAddNewModal.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'app/locales/en_US/website'
        - 'src/components/projects/locales/*/Project'

addNewWizardPages:
    path: 'src/components/claims/ng/views/addNewWizardPages.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'
    listeners:
        - { 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'cacheKey': 'ClaimStatusTypes', 'class': 'components\claims\models\ClaimStatusModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'cacheKey': 'ClaimPhases', 'class': 'components\claims\models\ClaimPhaseModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'cacheKey': 'ClaimTypes', 'class': 'components\claims\models\ClaimTypeModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\projects\form\ProjectBuilder'
            model: 'components\projects\models\ProjectAddressModel'
            cacheKey: 'ProjectAddressForm'
            formName: 'form'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ProjectAddressModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'claimLocationForm'
            dependencies:
                - { dependency: ClaimPhases, key: claimPhases, value: id, text: title }
                - { dependency: ClaimTypes, key: claimTypes, value: ClaimTypes_id, text: typeOfClaim }
                - { dependency: ClaimStatusTypes, key: claimStatus, value: ClaimStatusTypes_id, text: status }

initialJobsheetWizardPages:
    path: 'src/components/claims/ng/views/initialJobsheetWizardPages.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'
    listeners:
        - { 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel', 'cacheKey': 'ContactTypes' }
        - { 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        # build the form for Project Address
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\projects\form\ProjectBuilder'
            model: 'components\projects\models\ProjectAddressModel'
            cacheKey: 'ProjectAddressForm'
            formName: 'projectAddressForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
        # build the form for Claim Location
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ClaimLocationModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'claimLocationForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
        # build the form for Contact
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\contacts\form\ContactBuilder'
            model: 'components\contacts\models\ContactModel'
            cacheKey: 'ContactForm'
            formName: 'contactForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
                - { dependency: ContactTypes, key: contactTypes, value: ContactTypes_id, text: contactType }


claimEditModal:
    path: 'src/components/claims/ng/views/claimEditModal.php'
    listeners:
        - { 'cacheKey': 'ClaimStatusTypes', 'class': 'components\claims\models\ClaimStatusModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'cacheKey': 'ClaimPhases', 'class': 'components\claims\models\ClaimPhaseModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'cacheKey': 'ClaimTypes', 'class': 'components\claims\models\ClaimTypeModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
       # - { 'cacheKey': 'ClaimTypes', 'class': 'components\claims\models\ClaimType', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }

        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimBuilder'
            model: 'components\claims\models\ClaimModel'
            cacheKey: 'ClaimForm'
            formName: 'form'
            dependencies:
                - { dependency: ClaimPhases, key: claimPhases, value: id, text: title }
                - { dependency: ClaimTypes, key: claimTypes, value: ClaimTypes_id, text: typeOfClaim }
                - { dependency: ClaimStatusTypes, key: claimTypes, value: ClaimStatusTypes_id, text: status }


assignPMModal:
    path: 'src/components/claims/ng/views/assignPMModal.php'
    listeners:
        - { 'cacheKey': 'ProjectManagers', 'class': 'components\staff\models\ProjectManagerModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }


claimsAdminTab:
    path: 'src/components/claims/views/admin/claims/list.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'

claimsEditTab:
    path: 'src/components/claims/views/admin/claims/edit.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'
    listeners:
        - { 'cacheKey': 'Claims', 'class': 'components\claims\models\ClaimModel', 'event': 'filerender_start', 'listener': 'components\claims\listeners\LoadClaimByJobNumberListener', 'datasource': 'datasource1' }

        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimBuilder'
            model: 'components\claims\models\ClaimModel'
            cacheKey: 'ClaimForm'
            formName: 'form'
    #            dependencies:
    #                - { dependency: Vehicles, key: vehicles, value: id, text: number }
    #                - { dependency: ClaimPhases, key: claimPhases, value: id, text: title }
    #                - { dependency: ClaimStatusTypes, key: claimStatus, value: id, text: status }

claimLocationModal:
    path: 'src/components/claims/ng/views/claimsLocationModal.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'app/locales/*/website'
    listeners:
        - { 'class': 'components\vehicles\models\VehicleModel', 'cacheKey': 'Vehicles', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'class': 'components\claims\models\ClaimPhaseModel', 'cacheKey': 'ClaimPhases', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'class': 'components\claims\models\ClaimStatusModel', 'cacheKey': 'ClaimStatusTypes', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }

        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ClaimLocationModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'form'
            dependencies:
                - { dependency: Vehicles, key: vehicles, value: id, text: number }
                - { dependency: ClaimPhases, key: claimPhases, value: id, text: title }
                - { dependency: ClaimStatusTypes, key: claimStatus, value: id, text: status }



secondarySheet:
    path: 'src/components/claims/ng/views/secondarySheet.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'
    listeners:
        - { 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'cacheKey': 'ClaimStatusTypes', 'class': 'components\claims\models\ClaimStatusModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'cacheKey': 'ClaimPhases', 'class': 'components\claims\models\ClaimPhaseModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        - { 'cacheKey': 'ClaimTypes', 'class': 'components\claims\models\ClaimTypeModel', 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1' }
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\projects\form\ProjectBuilder'
            model: 'components\projects\models\ProjectAddressModel'
            cacheKey: 'ProjectAddressForm'
            formName: 'form'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ProjectAddressModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'claimLocationForm'
            dependencies:
                - { dependency: ClaimPhases, key: claimPhases, value: id, text: title }
                - { dependency: ClaimTypes, key: claimTypes, value: ClaimTypes_id, text: typeOfClaim }
                - { dependency: ClaimStatusTypes, key: claimStatus, value: ClaimStatusTypes_id, text: status }
                

secondarySheetAdminTab:
    path: 'src/components/claims/views/admin/secondarysheets/list.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'
                