## YAML Template.
---
claimsAddNewModal:
    path: 'src/components/claims/ng/views/claimsAddNewModal.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'app/locales/en_US/website'
        - 'src/components/projects/locales/*/Project'

addNewWizardPages:
    path: 'src/components/claims/ng/views/addNewWizardPages.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'
    listeners:
        - { 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\FormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\projects\form\ProjectBuilder'
            model: 'components\projects\models\ProjectAddressModel'
            cacheKey: 'ProjectAddressForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }

initialJobsheetWizardPages:
    path: 'src/components/claims/ng/views/initialJobsheetWizardPages.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'
    listeners:
        - { 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel', 'cacheKey': 'ContactTypes' }
        - { 'event': 'filerender_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        # build the form for Project Address
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\projects\form\ProjectBuilder'
            model: 'components\projects\models\ProjectAddressModel'
            cacheKey: 'ProjectAddressForm'
            formName: 'projectAddressForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
        # build the form for Claim Location
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\claims\form\ClaimLocationBuilder'
            model: 'components\claims\models\ClaimLocationModel'
            cacheKey: 'ClaimLocationForm'
            formName: 'claimLocationForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
        # build the form for Contact
        -
            event: 'filerender_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\contacts\form\ContactBuilder'
            model: 'components\contacts\models\ContactModel'
            cacheKey: 'ContactForm'
            formName: 'contactForm'
            dependencies:
                - { dependency: Provinces, key: provinces, value: id, text: province }
                - { dependency: ContactTypes, key: contactTypes, value: ContactTypes_id, text: contactType }

claimsAdminTab:
    path: 'src/components/claims/views/admin/claims/list.php'
    langFiles:
        - 'src/components/claims/locales/*/claims'
        - 'src/components/projects/locales/*/Project'