
admin_claim_edit:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "content": "src/components/claims/views/admin/claims/edit.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - claims
    head:
        - @components/claims/dist/bower_components/angular/angular.min.js
        - @components/claims/dist/bower_components/jquery/dist/jquery.min.js
        - @components/claims/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/claims/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/claims/dist/js/claims.concat.js
        #- @components/claims/dist/js/claims.min.js
    css:
        - @components/claims/dist/css/claims.min.css


claims_new_claim_wizard_1:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "content": "src/components/claims/views/admin/wizard1.php"
            "footer": "src/themes/default/templates/sections/footer.php"


admin_claims_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            leftnav: src/themes/default/templates/sections/left-nav.php
            "content": src/components/claims/views/admin/claims/list.php
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - claimsAdmin

    head:
        - @components/claims/dist/bower_components/angular/angular.min.js
        - @components/claims/dist/bower_components/jquery/dist/jquery.min.js
        - @components/claims/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/claims/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/bower_components/dropzone/dist/min/dropzone.min.js

    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/claims/dist/js/claims.concat.js

        #- @components/staff/dist/js/staff.min.js
    css:
        - @components/claims/dist/css/claims.min.css
        - @extensions/angular/dist/bower_components/dropzone/dist/dropzone.css


admin_claims_list:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
           # "section3": "src/components/staff/views/admin/staff-list.php"
            "featureslider-edit1": "src/components/claims/views/admin/edit.php"
            "featureslider-edit2": "src/components/claims/views/admin/edit2.php"
            "featureslider-edit3": "src/components/claims/views/admin/edit3.php"
            "featureslider-edit4": "src/components/claims/views/admin/edit4.php"
          #  "featureslider-edit5": "src/components/claims/views/admin/edit5.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - claimsAdmin
    head:
        - @components/claims/dist/bower_components/angular/angular.min.js
        - @components/claims/dist/bower_components/jquery/dist/jquery.min.js
        - @components/claims/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/claims/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/claims/dist/js/claims.concat.js
        #- @components/claims/dist/js/claims.min.js
    css:
        - @components/claims/dist/css/claims.min.css

admin_claims_edit:
    template: admin-2cols.php
    sections:
        -
            header: src/themes/default/templates/sections/admin-header.php
            leftnav: src/themes/default/templates/sections/left-nav.php
            content: src/components/claims/views/admin/claims/edit.php
            cards: src/components/claims/views/admin/claims/edit-cards.php
            footer: src/themes/default/templates/sections/footer.php
    angular:
        bootstrap_modules:
            - rootApp
            - claimsAdmin
          #  - xeditable
    head:
        - @components/claims/dist/bower_components/angular/angular.min.js
        - @components/claims/dist/bower_components/jquery/dist/jquery.min.js
        - @components/claims/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/claims/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/claims/dist/js/claims.concat.js
        #- @components/claims/dist/js/claims.min.js
       # - @extensions/xeditable/dist/js/xeditable-extension.concat.js
    css:
        - @components/claims/dist/css/claims.min.css
       # - @extensions/xeditable/ng/css/xeditable.css


admin_claims_initial_jobsheet:
    template: admin-2cols.php
    sections:
        -
            header: src/themes/default/templates/sections/admin-header.php
            content: src/components/claims/views/admin/claims/initial-jobsheet/form.php
            cards: src/components/claims/views/admin/claims/initial-jobsheet/form-cards.php
            footer: src/themes/default/templates/sections/footer.php
    angular:
        bootstrap_modules:
            - rootApp
            - claimsAdmin
    head:
        - @components/claims/dist/bower_components/angular/angular.min.js
        - @components/claims/dist/bower_components/jquery/dist/jquery.min.js
        - @components/claims/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/claims/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/bower_components/dropzone/dist/min/dropzone.min.js

    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/claims/dist/js/claims.concat.js

        #- @components/staff/dist/js/staff.min.js
    css:
        - @components/claims/dist/css/claims.min.css
        - @extensions/angular/dist/bower_components/dropzone/dist/dropzone.css


admin_claims_edit1:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/edit1.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claims_edit2:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/edit2.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claims_edit3:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/edit3.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claims_edit4:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/edit4.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claim_view:
    template: admin-list.php
    sections:
        -
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "header": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "content": "src/components/claims/views/admin/claims/edit.php"
            "footer": "src/themes/default/templates/sections/footer.php"

admin_claimlocation_view:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/locations-edit.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claimlocation_edit_work:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/locationswork-list.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claimlocation_work_history:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/locationswork-history.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claims_scheduling_list:
    template: admin-list-fullscreen.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/scheduling/views/grid-compressed.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claimlocations_by_claimid:



admin_claims_claim_photos_home:
    template: admin-fullscreen.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/claims/views/subnav.php"
            "section3": "src/components/claims/views/admin/parameters.php"
            #"section4": "src/components/claims/views/list-by-address.php"
            "section5": "src/themes/default/templates/sections/footer.php"


#-----------------------------start client portal section --------------------------------
claims_list:
    template: list-fullscreen.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/claims/views/subnav.php"
            "section3": "src/components/claims/views/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"

claims_view:
    template: list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/claims/views/subnav.php"
            "section3": "src/components/claims/views/leftnav.php"
            "section4": "src/components/claims/views/view.php"
            "section5": "src/themes/default/templates/sections/footer.php"

claims_list_by_projectaddress:
    template: list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/claims/views/subnav.php"
            #"section3": "src/components/claims/views/leftnav.php"
            "section4": "src/components/claims/views/list-by-address.php"
            "section5": "src/themes/default/templates/sections/footer.php"
            
claims_cost_cards_view:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/claims/views/admin/costCards/edit.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - claimsAdmin
    head:
        - @components/claims/dist/bower_components/angular/angular.min.js
        - @components/claims/dist/bower_components/jquery/dist/jquery.min.js
        - @components/claims/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/claims/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        - @components/claims/dist/js/claims.concat.js
    css:
        - @components/claims/dist/css/claims.min.css