             
            
claims_new_claim_wizard_1:   
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/subnav.php"
            #"section3": "src/components/claims/views/leftnav.php"
            "section4": "src/components/claims/views/admin/wizard1.php"
            "section5": "src/themes/default/templates/sections/footer.php"  
            
admin_claims_home:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "section2": "src/components/claims/views/admin/subnav.php"
           # "section3": "src/components/staff/views/admin/staff-list.php"
            "featureslider-edit1": "src/components/claims/views/admin/edit.php"
            "featureslider-edit2": "src/components/claims/views/admin/edit2.php"
            "featureslider-edit3": "src/components/claims/views/admin/edit3.php"
            "featureslider-edit4": "src/components/claims/views/admin/edit4.php"
          #  "featureslider-edit5": "src/components/claims/views/admin/edit5.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
    
admin_claims_list:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "featureslider": "src/components/claims/views/admin/view.php"
            "featureslider-edit1": "src/components/claims/views/admin/edit1.php"
            "featureslider-edit2": "src/components/claims/views/admin/edit2.php"
            "featureslider-edit3": "src/components/claims/views/admin/edit3.php"
            "featureslider-edit4": "src/components/claims/views/admin/edit4.php"
            "section3": "src/components/claims/views/admin/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_claims_edit1:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/edit1.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
admin_claims_edit2: 
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/edit2.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_claims_edit3:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/edit3.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_claims_edit4:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/edit4.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_claim_view:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/parameters.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_claimlocation_view:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/locations-edit.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_claimlocation_edit_work:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/locationswork-list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_claimlocation_work_history:   
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/claims/views/admin/locationswork-history.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
            
admin_claims_scheduling_list:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/claims/views/admin/subnav.php"
            "section3": "src/components/scheduling/views/grid-compressed.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
    
admin_claimlocations_by_claimid:
    
    
#-----------------------------start client portal section --------------------------------
claims_list:   
    template: list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/claims/views/subnav.php"
            "section3": "src/components/claims/views/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"  
            
claims_view:      
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/claims/views/subnav.php"
            "section3": "src/components/claims/views/leftnav.php"
            "section4": "src/components/claims/views/view.php"
            "section5": "src/themes/default/templates/sections/footer.php"  
                    
claims_list_by_projectaddress:     
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/claims/views/subnav.php"
            #"section3": "src/components/claims/views/leftnav.php"
            "section4": "src/components/claims/views/list-by-address.php"
            "section5": "src/themes/default/templates/sections/footer.php"          