## YAML Template.
---

claims_list_new: 'src/components/claims/views/widgets/new-count.php'
    
claims_list_open:  'src/components/claims/views/widgets/open-count.php' 

claims_list: 'src/components/claims/views/widgets/list-all.php' 

claims_view_header: 'src/components/claims/views/widgets/claim-header.php'

claims_locations_instructions: 'src/components/claims/views/widgets/special-instructions.php'

claims_ecd_accuracy: 'src/components/claims/views/widgets/ecd-accuracy.php'

claims_icon_list: 'src/components/claims/views/widgets/icon-list.php'

claims_location_areas: 'src/components/claims/views/widgets/location-areas-chart.php'

claims_location_comments: 'src/components/claims/views/widgets/location-comments.php'

claim_photo_count: 'src/components/claims/views/widgets/photo-count.php'

claim_photo_list: 'src/components/claims/views/widgets/photos-list.php'

claim_photos_upload: 'src/components/claims/views/widgets/photos-upload.php'

admin_claims_list_claim_photos: 'src/components/claims/views/widgets/photos-list.php'