

admin_surveys_edit:
    name: utf8
    
admin_surveys_save:
    name: utf8
    
admin_surveys_list:
    name: utf8
    
admin_surveys_answers_save:  
    answer: utf8 
    
admin_surveys_answers_list:  
    answer: utf8   
    
admin_surveys_answers_edit:  
    answer: utf8  
    name: utf8
    
admin_surveys_questions_save:  
    question: utf8 
    
admin_surveys_questions_list:  
    question: utf8   
    
admin_surveys_questions_edit:  
    question: utf8  
    answer: utf8  
    
admin_surveys_answers_search:   
    keywords: utf8
    answer: utf8
    
admin_surveys_panes_questions_list:
    question: utf8
    
admin_surveys_respond_by_permalink:  
    name: utf8
    question: utf8
    answer: utf8
    
admin_surveys_view_responses:  
    name: utf8
    question: utf8
    answer: utf8   
    
admin_surveys_questions_search:
    term: utf8
    keywords: utf8
    question: utf8
    answer: utf8
    
admin_surveys_panes_search:
   # term: utf8
    #keywords: utf8
    #title: utf8
    
admin_surveys_panes_save:
    title: utf8
    description: utf8
    
admin_surveys_panes_edit:
    title: utf8
    description: utf8
    
admin_surveys_panes_list:
    title: utf8
    description: utf8
    
    
admin_surveys_pages_search:
    #term: utf8
    #keywords: utf8
    #name: utf8
    
    
    