


cms_view_page_1:
    pattern: restoration/*
    listeners:
        - { 'event': 'response_start', 'cacheKey': 'CmsPage', 'listener': 'core\components\cms\listeners\LoadByPermalinkCachableListener', 'datasource': 'datasource1', 'class': 'components\cms\models\PageModel'}
    defaults:
        component: components\cms\CmsComponent
        controller: components\cms\controllers\PagesController
        model: components\cms\models\PageModel
        method: viewByPermalink
        view: core\views\TemplateView
        viewKey: cms_view_page_1
        datasource: datasource1
 

cms_view_page_2:
    pattern: restoration/*/*
    listeners:
        - { 'event': 'response_start', 'cacheKey': 'CmsPage', 'listener': 'core\components\cms\listeners\LoadByPermalinkCachableListener', 'datasource': 'datasource1', 'class': 'components\cms\models\PageModel'}
    defaults:
        component: components\cms\CmsComponent
        controller: components\cms\controllers\PagesController
        model: components\cms\models\PageModel
        method: viewByPermalink
        view: core\views\TemplateView
        viewKey: cms_view_page_2
        datasource: datasource1    
        


cms_view_page_3:
    pattern: restoration/*/*/*
    listeners:
        - { 'event': 'response_start', 'cacheKey': 'CmsPage', 'listener': 'core\components\cms\listeners\LoadByPermalinkCachableListener', 'datasource': 'datasource1', 'class': 'components\cms\models\PageModel'}
    defaults:
        component: components\cms\CmsComponent
        controller: components\cms\controllers\PagesController
        model: components\cms\models\PageModel
        method: viewByPermalink
        view: core\views\TemplateView
        viewKey: cms_view_page_3
        datasource: datasource1          