index:   
    template: portal-list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/portal-header.php"
            "payload": "src/components/cms/views/view.php"
            "footer": "src/themes/default/templates/sections/footer.php"
            

cms_view_page_1:    
    template: portal-list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/portal-header.php"
            "payload": "src/components/cms/views/view.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    
                
            
cms_view_page_2:    
    template: portal-list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/portal-header.php"
            "payload": "src/components/cms/views/view.php"
            "footer": "src/themes/default/templates/sections/footer.php"
            
cms_view_page_3:    
    template: portal-list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/portal-header.php"
            "payload": "src/components/cms/views/view.php"
            "footer": "src/themes/default/templates/sections/footer.php"       

cms_view_page_portal_1:    
    template: portal-list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/portal-header.php"
            "payload": "src/components/cms/views/view.php"
            "footer": "src/themes/default/templates/sections/footer.php"            