

cms_view_page_1:    
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/cms/views/view.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
                
            
cms_view_page_2:    
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/cms/views/view.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
cms_view_page_3:    
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/cms/views/view.php"
            "section4": "src/themes/default/templates/sections/footer.php"            