## YAML Template.
---
sortByButton:
    path: 'src/extensions/angular/ng/views/sortByButton.php'
    langFiles:
        - 'src/components/staff/locales/*/staff'

commentsTemplate:
    path: 'src/extensions/angular/ng/views/comments.php'    
    langFiles:
        - 'src/components/accounting/locales/*/accounting'