
#-------------------- event types -----------------------
super_keys_keytypes_list:     
    template: super-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"           
            "section3": "src/components/keys/views/admin/types/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
super_keys_list:          
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"           
            "section3": "src/components/keys/views/admin/keys/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"       
            
super_keys_edit:            
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"           
            "section3": "src/components/keys/views/admin/keys/edit.php"
            "section4": "src/themes/default/templates/sections/footer.php" 