

fields:
    - name:
        - 
            class: Required     
            failkey: VALIDATION_REQUIRED_FIELD
        -
            class: AlphaNumeric
            failkey: VALIDATION_INVALID_FIELD
            params:
                - maxlength: 70 
    - address:
        - 
            class: Required     
            failkey: VALIDATION_REQUIRED_FIELD
        -
            class: AlphaNumeric
            failkey: VALIDATION_INVALID_FIELD
            params:
                - maxlength: 70 
    - city:
        - 
            class: Required     
            failkey: VALIDATION_REQUIRED_FIELD
        -
            class: AlphaNumeric
            failkey: VALIDATION_INVALID_FIELD
            params:
                - maxlength: 50 
    - telephone:
        - 
            class: Required     
            failkey: VALIDATION_REQUIRED_FIELD
        -
            class: AlphaNumeric
            failkey: VALIDATION_INVALID_FIELD
            params:
                - maxlength: 70 
    - url:
        - 
            class: Required     
            failkey: VALIDATION_REQUIRED_FIELD