

basicmenu_ceilingbar:
    pattern: basicmenu/ceilingbar
    listeners:
        #- { 'event': 'request_start', 'listener': 'components\contacts\listeners\LoadContactByIdListener', 'datasource': 'datasource1' }
    defaults:
        component: core\components\basicmenu\BasicMenuComponent
        controller: core\components\basicmenu\controllers\BasicMenuController
        model: core\components\basicmenu\models\BasicMenuModel
        method: view
        view: core\views\TemplateView
        viewKey: basicmenu_ceilingbar
        datasource: datasource1
        langFiles: 
            - 'app/framework/core/components/basicmenu/locales/*/menu'

    