admin_blogs_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "subnav": "src/framework/core/components/blogs/views/admin/subnav.php"
            "content": "src/framework/core/components/blogs/views/admin/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - blogsAdmin
    head:
        - @components/blogs/dist/bower_components/angular/angular.min.js
        - @components/blogs/dist/bower_components/jquery/dist/jquery.min.js
        - @components/blogs/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/blogs/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/bower_components/dropzone/dist/min/dropzone.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/blogs/dist/js/blogs.concat.js
        #- @components/blogs/dist/js/blogs.min.js
    css:
        - @core/components/blogs/dist/css/blogs.min.css
        - @extensions/angular/dist/bower_components/dropzone/dist/dropzone.css


admin_blogs_list:
    template: admin-list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "subnav": "src/framework/core/components/blogs/views/admin/subnav.php"
            "content": "src/framework/core/components/blogs/views/admin/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
 
admin_blogs_calendar:
    template: admin-list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "subnav": "src/framework/core/components/blogs/views/admin/subnav.php"
            "content": "src/framework/core/components/blogs/views/calendar.php"
            "footer": "src/themes/default/templates/sections/footer.php"

admin_blogs_edit:
    template: admin-list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "subnav": "src/framework/core/components/blogs/views/admin/subnav.php"
            "content": "src/framework/core/components/blogs/views/admin/edit.php"
            "footer": "src/themes/default/templates/sections/footer.php"
            
website_blogs_list: 
    template: list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/header.php"
            "subnav": "src/framework/core/components/blogs/views/subnav.php"
            "payload": "src/framework/core/components/blogs/views/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"   
            
website_blogs_view:   
    template: list.php
    sections: 
        -
            "header": "src/themes/default/templates/sections/header.php"
            "subnav": "src/framework/core/components/blogs/views/subnav.php"
            "payload": "src/framework/core/components/blogs/views/view.php"
            "footer": "src/themes/default/templates/sections/footer.php"     
          
website_blogs_feed:     
    template: newsfeed.php
    sections: 
        -
            "header": "src/framework/core/components/blogs/views/feed.php"     
            
website_blogs_minimenu:   
    template: newsfeed.php
    sections: 
        -
            "header": "src/framework/core/components/blogs/views/adminminimenu.php"          