

admin_departments_list:
    pattern: super/departments/*/*
    defaults:
        component: components\departments\DepartmentsComponent
        controller: components\departments\controllers\DepartmentsController
        model: components\departments\models\DepartmentModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_departments_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [GET]

     

admin_departments_edit:
    pattern: super/departments/*
    defaults:
        component: components\departments\DepartmentsComponent
        controller: components\departments\controllers\DepartmentsController
        model: components\departments\models\DepartmentModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_departments_edit
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [GET]     
     
admin_departments_save:
    pattern: super/departments/*
    defaults:
        component: components\departments\DepartmentsComponent
        controller: components\departments\controllers\DepartmentsController
        model: components\departments\models\DepartmentModel
        method: save
        view: core\views\JSONView
        viewKey: admin_departments_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [POST] 
    
admin_departments_remove:
    pattern: super/departments/remove/*
    defaults:
        component: components\departments\DepartmentsComponent
        controller: components\departments\controllers\DepartmentsController
        model: components\departments\models\DepartmentModel
        method: setInactive
        view: core\views\JSONView
        viewKey: admin_departments_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [POST]     
    