

#----------------- cookie info ----------------------

cookies:
    secure: true
    salt: D!dYewKn0wTh3En1gm@D3v1c#w@zaF*rM1dabL3Encyp+i0nD3v!s?
    name: phoenix_restorations
    
application:
    #possible choices: debug|production
    mode: debug

blog:
    caching: true
    
cms:
    caching: true
