

#this file is to demonstrate how multiple data sources can be used within the
#system. each yaml node for the components has a datasource key - those keys
#are the names of these datasources defined here. this allows you to specify
#unique datasources at the request level rather than at a global or module level.

api3:
    class: core\datasources\ProxyDataSource

    credentials:
        baseUrl: http://192.168.0.85/v3
        format: json
        headers:
            serverName: api-server
            serverAuth: $1$lIDKkGiyJVn2bZSQdxwEYW0

api1:
    class: extensions\datasources\V1ProxyDataSource

    credentials:
        baseUrl: http://192.168.0.85/api_v1/ws_server.php
        format: json
        headers:
            serverName: api-server
            serverAuth: $1$lIDKkGiyJVn2bZSQdxwEYW0

mysql_local:
    class: core\datasources\DBConnectionAdapter
    credentials:
        host: localhost
        username: root
        password: rGinSeng1@#
        dbName: BHDB5


mssql_2000:
    class: core\datasources\MSSQLConnectionAdapter
    credentials:
        host: 192.168.0.253
        username: James1
        password: James1@#
        dbName: BHDB4

datasource2:
    class: core\datasources\FileDataSource

datasource3:
    class: core\datasources\DBConnectionAdapter
    credentials:
        host: localhost
        username: yourusername
        password: yourpassword
        dbName: yetanotherBDtoconnectto


datasource4:
    class: core\datasources\RestConnectionAdapter
    credentials:
        baseUrl: http://someurlforrestAPI.com
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: yourserverIDgoeshere



database:
    host: localhost
    username: yourusername
    password: yourpassword
    dbName: yourdbname

    mysql:
        class: 'Gossamer\Pesedget\Database\DBConnection'
        credentials:
            host: localhost
            username: ourusername
            password: yourpassword
            dbName: yourdbname
    default: mysql


            
