
datasource1:
    class: core\datasources\RestDataSource
    credentials: 
        baseUrl: http://192.168.2.252
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: bQd18aba1df45jk7858c8ae88a57fa30

datasource2:
    class: core\datasources\FileDataSource

datasource3:
    class: core\datasources\DBConnectionAdapter
    credentials:
        host: localhost
        username: phoenixdave
        password: 0s1r15
        dbName: phoenix_local

        
datasource4:
    class: core\datasources\RestConnectionAdapter
    credentials: 
        baseUrl: http://192.168.2.252
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: bQd18aba1df45jk7858c8ae88a57fa30        
            


database:  
    host: localhost
    username: root
    password: isnothere
    dbName: phoenix_local
    
    mysql:
        class: 'Gossamer\Pesedget\Database\DBConnection'
        credentials:
            host: localhost
            username: phoenixdave
            password: 0s1r15
            dbName: phoenix_local
    default: mysql            
    
