
datasource1:
    class: core\datasources\RestDataSource
    credentials: 
        baseUrl: http://192.168.1.24
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: bQd18aba1df45jk7858c8ae88a57fa30

datasource2:
    class: core\datasources\FileDataSource

datasource3:
    class: core\datasources\DBConnectionAdapter
    credentials:
        host: localhost
        username: dave
        password: isnothere
        dbName: shoppingcart
        
datasource4:
    class: core\datasources\RestConnectionAdapter
    credentials: 
        baseUrl: http://192.168.1.24
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: bQd18aba1df45jk7858c8ae88a57fa30        
            


database:  
    host: localhost
    username: dave
    password: isnothere
    dbName: shoppingcart
    
    mysql:
        class: 'Gossamer\Pesedget\Database\DBConnection'
        credentials:
            host: localhost
            username: dave
            password: isnothere
            dbName: shoppingcart
    default: mysql            
    
