

#this file is to demonstrate how multiple data sources can be used within the
#system. each yaml node for the components has a datasource key - those keys
#are the names of these datasources defined here. this allows you to specify
#unique datasources at the request level rather than at a global or module level.

datasource1:
    class: core\datasources\RestDataSource

    credentials:
        baseUrl: http://firstsamplerestdomain.com
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: someserverauthexpectedonotherendgoeshere

datasource2:
    class: core\datasources\FileDataSource

datasource3:
    class: core\datasources\DBConnectionAdapter
    credentials:
        host: localhost
        username: yourusername
        password: yourpassword
        dbName: yetanotherBDtoconnectto


datasource4:
    class: core\datasources\RestConnectionAdapter
    credentials: 
        baseUrl: http://someurlforrestAPI.com
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: yourserverIDgoeshere



database:
    host: localhost
    username: yourusername
    password: yourpassword
    dbName: yourdbname

    mysql:
        class: 'Gossamer\Pesedget\Database\DBConnection'
        credentials:
            host: localhost
            username: ourusername
            password: yourpassword
            dbName: yourdbname
    default: mysql


pdf_proxy:
    class: core\datasources\RemoteFileDataSource

    credentials:
        baseUrl: http://localhost:8088/ #or whatever url you want
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: quantumunit
            

java_proxy:
    class: extensions\proxyserver\datasources\ProxyDatasource

    credentials:
        baseUrl: http://localhost:8082/ #or whatever url you want
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: yourserverauthhere            