


#admin_area:
#    pattern: admin/cart/sales/*/*
#    authentication: simple_auth
#    fail_url: admin/login

admin_login_reset:
    pattern: admin/login/reset
    security: false
    methods: [POST]

admin_login_confirmreset_submit:
    pattern: admin/login/confirmreset/*
    security: false
    methods: [POST]


admin_login_get:
    pattern: admin/login
    security: false
    methods: [GET]

admin_login_submit:
    pattern: staff/staff/login
    authentication: staff_login_auth
    methods: [GET]

admin_area2:
    pattern: /admin
    authentication: simple_auth
    fail_url: admin/login




portal_login_submit:
    pattern: portal/entrance
    authentication: contact_login_auth
    fail_url: portal/entrance
    methods: [POST]



portal_invite_login_submit:
    pattern: portal/contacts/invite/login
    authentication: invite_login_auth
    fail_url: portal/contacts/invite/login
    methods: [POST]



#backoffice section
backoffice_login_get:
    pattern: backoffice/login
    authorization: server_by_key_auth
    methods: [GET]


backoffice_login_post:
    pattern: backoffice/login
    authorization: server_by_key_auth
    methods: [POST]


backoffice_apikeys_list:
    pattern: backoffice/security/apikeys
    authorization: server_by_key_auth
    methods: [GET]


backoffice_apikeys_view:
    pattern: backoffice/security/apikeys/*
    authorization: server_by_key_auth
    methods: [GET]


backoffice_apikeys_save:
    pattern: backoffice/security/apikeys/*
    authorization: server_by_key_auth
    methods: [POST]

backoffice_apikeys_remove:
    pattern: backoffice/security/remove
    authorization: server_by_key_auth
    methods: [POST]



#invoicing module
renewal_invoice:
    pattern: renewal
    authorization: server_by_key_auth
    methods: [POST]

#fetch_invoice:
#    pattern: fetchInvoice
#    authorization: member_info_auth
#    methods: [POST]



invoicing:
    pattern: invoicing
    authorization: invoice_shop_auth
    methods: [POST]



invoicing:
    pattern: invoicing
    authorization: invoice_shop_auth
    methods: [POST]


#members module
#members_reports:
#    pattern: members/*/reports
#    authorization: member_info_auth
#    methods: [POST]

members_receipts:
    pattern: members/*/receipts/*
    authorization: member_info_auth
    methods: [GET]

members_promote_v3:
    pattern: promote/*
    authorization: member_info_auth
    methods: [POST]


members_reports_v1:
    pattern: member_reports/*
    authorization: member_info_auth
    methods: [POST]

memberSales_v3:
    pattern: memberSales/*
    authorization: member_info_auth
    methods: [POST]

member_get:
    pattern: member/*
    authorization: member_info_auth
    methods: [GET]

#this route generates a new Member_ID on save, cannot really test by memberId
#members_v3:
#    pattern: members
#    authorization: member_info_auth
#    methods: [POST]


members_prefixstatus:
    pattern: member/editPrefixStatus
    authorization: server_by_key_auth
    methods: [POST]

members_memberbylevel:
    pattern: memberByLevel
    authorization: member_prefix_auth
    methods: [POST]


members_update:
    pattern: members/*/update
    authorization: member_info_auth
    methods: [POST]


members_sales:
    pattern: memberSales/*
    authorization: member_info_auth
    methods: [POST]

member_uplines:
    pattern: memberUplines
    authorization: member_info_auth
    methods: [POST]


#member_search:
#    pattern: memberSearch
#    authorization: member_info_auth
#    methods: [POST]


#receipts module
receipt_details:
    pattern: receiptDetails/*
    authorization: receipt_info_auth
    methods: [GET]

company_reports:
    pattern: reports
    authorization: report_info_auth
    methods: [POST]

receipt_backdate:
    pattern: receipt/backdate
    authorization: receipt_backdate_auth
    methods: [POST]

receipt_comments:
    pattern: receiptComments/*
    authorization: receipt_comments_auth
    methods: [GET]






#reports module - not yet started

#reports:
#    pattern: renewal
#    authorization: server_by_key_auth
#    methods: [POST]


#postalcodes module

postalcode_valid:
    pattern: valid_postalcode
    authorization: server_by_key_auth
    methods: [GET]


zipcode_valid:
    pattern: valid_zipcode
    authorization: server_by_key_auth
    methods: [GET]