



admin_login_get:
    pattern: admin/login
    security: false
    methods: [GET]

admin_login_submit:
    pattern: staff/staff/login
    authentication: staff_login_auth
    methods: [GET]

admin_area2:
    pattern: /admin
    authentication: simple_auth
    fail_url: admin/login




portal_login_submit:
    pattern: portal/entrance
    authentication: contact_login_auth
    fail_url: portal/entrance
    methods: [POST]

