

admin_home:
    text_key: 'ADMIN_HOME'
    pattern: '/admin/home'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
        
admin_contactus:
    text_key: 'ADMIN_CONTACTUS'
    pattern: '/admin/contact/0/20'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
        
staff_list:
    text_key: 'ADMIN_STAFF'
    pattern: '/admin/staff/0/20'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF

        
admin_scoping:
    text_key: 'ADMIN_SCOPING'
    pattern: '/admin/scoping/requests/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_SCOPER
        - IS_PROJECT_MANAGER
        
admin_claims:
    text_key: 'ADMIN_CLAIMS'
    pattern: '/admin/claims/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_ADMIN
        - IS_STAFF
        
admin_contents:
    text_key: 'ADMIN_CONTENTS'
    pattern: '/admin/contents/jobs/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
        
samples_list:
    text_key: 'ADMIN_SAMPLES'
    pattern: '/admin/samples/0/20'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
        
admin_contacts:
    text_key: 'ADMIN_CONTACTS'
    pattern: '/admin/contacts/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
        
admin_inventory:
    active: false
    text_key: 'ADMIN_INVENTORY'
    pattern: '/admin/inventory'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
        
admin_keys:
    active: false
    text_key: 'ADMIN_KEYS'
    pattern: '/admin/keys/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
        
admin_notifications:
    active: true
    text_key: 'ADMIN_NOTIFICATIONS'
    pattern: '/admin/notifications/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
        
admin_messages:
    active: true
    text_key: 'ADMIN_MESSAGES'
    pattern: '/admin/messaging/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
        
admin_reminders:
    active: true
    text_key: 'ADMIN_REMINDERS'
    pattern: '/admin/reminders/0/20'
    display_roles:
        - IS_STAFF
        
admin_satisfaction:
    active: false
    text_key: 'ADMIN_SATISFACTION'
    pattern: '/admin/satisfaction'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_PROJECT_MANAGER
        - IS_PM_ASSISTANT
        
admin_call_matrix:
    active: false
    text_key: 'ADMIN_CALL_MATRIX'
    pattern: '/admin/callmatrix/0/14'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_PROJECT_MANAGER
        - IS_PM_ASSISTANT
        
admin_deficiencies:
    active: false
    text_key: 'ADMIN_DEFICIENCIES'
    pattern: '/admin/deficiencies/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        
admin_subcontractors:
    active: false
    text_key: 'ADMIN_SUBCONTRACTORS'
    pattern: '/admin/subcontractors/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        
admin_accounting:
    active: false
    text_key: 'ADMIN_ACCOUNTING'
    pattern: '/admin/accounting'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_PROJECT_MANAGER
        - IS_PM_ASSISTANT
        - IS_ACCOUNTING
        
admin_workperformed:
    active: true
    text_key: 'ADMIN_WORKPERFORMED'
    pattern: '/admin/workperformed/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_PROJECT_MANAGER
        - IS_PM_ASSISTANT
        - IS_ACCOUNTING
         
        
        
admin_environmental:
    active: true
    text_key: 'ADMIN_ENVIRONMENTAL'
    pattern: '/admin/environmental/0/20'
    display_roles:
        - IS_ADMINISTRATOR         
        - IS_STAFF 
    

admin_cms:
    active: true
    text_key: 'ADMIN_CMS'
    pattern: '/admin/cms/pages/0/20'
    display_roles:
        - IS_ADMINISTRATOR         
        - IS_EDITOR 
        
        
projects:
    active: true
    text_key: 'ADMIN_PROJECTS'
    pattern: '/admin/projects/0/20'
    display_roles:
        - IS_ADMINISTRATOR         
        - IS_EDITOR 
        - IS_STAFF
    
        
        
incidents:
    active: true
    text_key: 'ADMIN_INCIDENTS'
    pattern: '/admin/incidents/0/20'
    display_roles:
        - IS_ADMINISTRATOR         
        - IS_EDITOR 
  

        
surveys:
    active: true
    text_key: 'ADMIN_SURVEYS'
    pattern: '/admin/surveys/0/20'
    display_roles:
        - IS_ADMINISTRATOR         
        - IS_EDITOR 
        
events: 
    active: true
    text_key: 'ADMIN_EVENTS'
    pattern: '/admin/events/0/20'
    display_roles:
        - IS_ADMINISTRATOR         
        - IS_EDITOR 
        - IS_STAFF

#-------------------CLIENT PORTAL SECTION--------------------

portal_home:
    active: true
    text_key: 'PORTAL_HOME'
    pattern: '/portal/home'
    display_roles:
        - IS_PORTAL_MANAGER         
      
portal_contacts_list:
    active: true
    text_key: 'PORTAL_CONTACTS_LIST'
    pattern: '/portal/contacts/list/0/20'
    display_roles:
        - IS_PORTAL_MANAGER            


portal_contacts_settings:
    active: true
    text_key: 'PORTAL_CONTACT_SETTINGS'
    pattern: '/portal/contacts/settings'
    display_roles:
        - IS_PORTAL_MANAGER  
        - IS_CUSTOMER   
        

portal_projects_list:
    active: true
    text_key: 'PORTAL_PROJECTS_LIST'
    pattern: '/portal/projects/company'
    display_roles:
        - IS_PORTAL_MANAGER  
                
                
portal_events_list:
    active: true
    text_key: 'PORTAL_EVENTS_LIST'
    pattern: '/portal/events/0/20'
    display_roles:
        - IS_PORTAL_MANAGER  
                
                        
#--------------------------main website ----------------------

website_services:
    active: true
    text_key: 'WEBSITE_SERVICES'
    pattern: '/restoration/services'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER   
        
website_login:
    active: true
    text_key: 'WEBSITE_LOGIN'
    pattern: '/portal/entrance'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER           
        

website_blogs_list:
    active: true
    text_key: 'WEBSITE_BOGS_LIST'
    pattern: '/blogs/0/20'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER       
        
website_contact:
    active: true
    text_key: 'WEBSITE_CONTACT'
    pattern: '/contact/contactus'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER      
        
website_faqs:
    active: true
    text_key: 'WEBSITE_FAQS'
    pattern: '/restoration/frequently-asked-restoration-questions'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER    

website_about:
    active: true
    text_key: 'WEBSITE_ABOUT'
    pattern: '/restoration/about-phoenix-restorations'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER          