

admin_home:
    text_key: 'ADMIN_HOME'
    pattern: '/admin/home'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
        
super_user_home:
    text_key: 'SUPER_USER_HOME'
    pattern: '/super/home'
    display_roles:
        - IS_SUPER_USER
        
admin_contactus:
    text_key: 'ADMIN_CONTACTUS'
    pattern: '/admin/contact/0/20'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
        
staff_list:
    text_key: 'ADMIN_STAFF'
    pattern: '#'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
    children:
        staff_list:
            text_key: 'ADMIN_STAFF'
            pattern: '/admin/staff/0/20'
            display_roles:
                - IS_ADMIN
                - IS_ADMINISTRATOR
                - IS_STAFF
        staff_add_new:
            text_key: 'ADMIN_STAFF_ADD_NEW'
            pattern: '/admin/staff/0'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_HR_MANAGER

        
admin_contacts:
    text_key: 'ADMIN_CONTACTS'
    pattern: '/admin/contacts/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
    children:
        contacts_list_all:
            text_key: 'ADMIN_CONTACTS_LIST_ALL'
            pattern: '/admin/contacts/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_STAFF
                - IS_PROJECT_MANAGER  
        contacts_add_new:
            text_key: 'ADMIN_CONTACTS_ADD_NEW'
            pattern: '/admin/contacts/0'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_STAFF
                - IS_PROJECT_MANAGER 
                - IS_PMA  
        contacts_companies_listall:
            text_key: 'ADMIN_COMPANIES_LIST_ALL'
            pattern: '/admin/companies/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_STAFF
                - IS_PROJECT_MANAGER 
                - IS_PMA
        contacts_add_new_company:
            text_key: 'ADMIN_COMPANIES_ADD_NEW'
            pattern: '/admin/companies/0'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_STAFF
                - IS_PROJECT_MANAGER 
                - IS_PMA
      
admin_notifications:
    active: true
    text_key: 'ADMIN_NOTIFICATIONS'
    pattern: '/admin/notifications/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
       
admin_cms:
    active: true
    text_key: 'ADMIN_CMS'
    pattern: '/admin/cms/pages/0/20'
    display_roles:
        - IS_ADMINISTRATOR         
        - IS_EDITOR 
    children:
        admin_cms_list_all:
            active: true
            text_key: 'ADMIN_CMS_LIST_ALL_PAGES'
            pattern: '/admin/cms/pages/0/20'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR 
        admin_cms_add_new:
            active: true
            text_key: 'ADMIN_CMS_ADD_NEW_PAGE'
            pattern: '/admin/cms/pages/0'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR 
        admin_cms_list_all_sections:
            active: true
            text_key: 'ADMIN_CMS_LIST_ALL_SECTIONS'
            pattern: '/admin/cms/sections/0/20'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR
        admin_cms_list_all_blogs:
            active: true
            text_key: 'ADMIN_CMS_LIST_ALL_BLOGS'
            pattern: '/admin/cms/blogs/0/20'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR 
        admin_cms_add_new_blog:
            active: true
            text_key: 'ADMIN_CMS_ADD_NEW_BLOGS'
            pattern: '/admin/cms/blogs/0'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR  
        
cart: 
    active: true
    text_key: 'NAV_ADMIN_CART'
    pattern: '/admin/cart/sales/0/20'
    display_roles:
        - IS_ADMINISTRATOR         
        - IS_EDITOR 
        - IS_STAFF        
    children:
        cart_categories: 
            active: true
            text_key: 'NAV_CATEGORIES'
            pattern: '/admin/cart/categories'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR 
                - IS_STAFF 
        cart_products: 
            active: true
            text_key: 'NAV_PRODUCTS'
            pattern: '/admin/cart/products/0/20'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR 
                - IS_STAFF 
        cart_sales: 
            active: true
            text_key: 'NAV_SALES'
            pattern: '/admin/cart/sales/0/20'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR 
                - IS_STAFF 
        cart_variants: 
            active: true
            text_key: 'NAV_VARIANTS'
            pattern: '/admin/cart/variants'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR 
                - IS_STAFF 
        cart_states: 
            active: true
            text_key: 'NAV_STATES'
            pattern: '/admin/cart/states'
            display_roles:
                - IS_ADMINISTRATOR         
                - IS_EDITOR 
                - IS_STAFF 

#-------------------CLIENT PORTAL SECTION--------------------

         
portal_contacts:
    active: true
    text_key: 'PORTAL_CONTACTS_LIST'
    pattern: '/portal/contacts/list/0/20'
    display_roles:
        - IS_PORTAL_MANAGER          

           
                
                        
#--------------------------main website ----------------------

website_home:
    active: true
    text_key: 'NAV_HOME'
    pattern: '/'
    title: 'asian home decor'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER   
        
website_login:
    active: true
    text_key: 'WEBSITE_LOGIN'
    pattern: '/portal/entrance'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER           
        

website_blogs_list:
    active: true
    text_key: 'WEBSITE_BOGS_LIST'
    pattern: '/blogs/0/20'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER       
        

website_faqs:
    active: true
    text_key: 'WEBSITE_FAQS'
    pattern: '/restoration/frequently-asked-restoration-questions'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER    

website_about:
    active: true
    text_key: 'NAV_ARTIST_PROFILE'
    pattern: '/about'
    title: 'about chinese good fortune wall tablets'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER  
    children:
       website_glen:
            active: true
            text_key: 'NAV_GLEN_MEIKLE'
            pattern: '/glen-meikle'
            title: 'glen meikle'
            display_roles:
                - IS_ANONYMOUS 
                - IS_CUSTOMER 
       website_wall_tablets:
            active: true
            text_key: 'NAV_WALL_TABLETS'
            pattern: '/wall-tablets'
            title: 'wall art tablets'
            display_roles:
                - IS_ANONYMOUS 
                - IS_CUSTOMER
                
website_cart:
     active: true
     text_key: 'NAV_CART'
     pattern: '/collection'
     title: 'wall art tablets'
     display_roles:
         - IS_ANONYMOUS 
         - IS_CUSTOMER  
         

website_design:
    active: true
    text_key: 'NAV_DESIGN'
    pattern: '/design'
    title: 'designer wall art tablets'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER   
    children:
        website_design1:
            active: true
            text_key: 'NAV_LAYOUT_1'
            pattern: '/design'
            title: 'designer wall art tablets'
            display_roles:
                - IS_ANONYMOUS 
                - IS_CUSTOMER 
        website_design2:
            active: true
            text_key: 'NAV_LAYOUT_2'
            pattern: '/design2'
            title: 'designer wall art tablets'
            display_roles:
                - IS_ANONYMOUS 
                - IS_CUSTOMER 
        

website_inspiration:
    active: true
    text_key: 'NAV_INSPIRATION'
    pattern: '/inspiration'
    title: 'designer wall art'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER    

website_contact:
    active: true
    text_key: 'NAV_CONTACT'
    pattern: '/contact'
    display_roles:
        - IS_ANONYMOUS 
        - IS_CUSTOMER      
        
        