

admin_home:
    text_key: 'ADMIN_HOME'
    pattern: '/admin/home'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
        - IS_SUPER_USER
        
        
admin_deficienies:
    text_key: 'ADMIN_DEFICIENCIES'
    pattern: '/super/deficiencies/0/20'
    display_roles:
        - IS_SUPER_USER
    children:        
        deficiencies_statuscodes:
            text_key: 'ADMIN_DEFICIENCIES_STATUS_CODES'
            pattern: '/super/deficiencies/codes/0/20'
            display_roles:
                - IS_SUPER_USER
        deficiencies_types:
            text_key: 'ADMIN_DEFICIENCIES_STATUS_CODES'
            pattern: '/super/deficiencies/types/0/20'
            display_roles:
                - IS_SUPER_USER
        urgency_types:
            text_key: 'ADMIN_URGENCY_TYPES'
            pattern: '/super/urgency/types/0/20'
            display_roles:
                - IS_SUPER_USER
                
admin_general:
    text_key: 'ADMIN_GENERAL'
    pattern: '/super/general'
    display_roles:
        - IS_SUPER_USER
    children:    
        admin_departments:
            text_key: 'ADMIN_DEPARTMENTS'
            pattern: '/super/departments/0/20'
            display_roles:
                - IS_SUPER_USER    
        admin_documents:
            text_key: 'ADMIN_DOCUMENTS'
            pattern: '/super/documents/0/20'
            display_roles:
                - IS_SUPER_USER
        admin_departments:
            text_key: 'ADMIN_DEPARTMENTS'
            pattern: '/super/departments/0/20'
            display_roles:
                - IS_SUPER_USER   
        admin_keys:
            text_key: 'ADMIN_KEY_TYPES'
            pattern: '/super/keys/types/0/20'
            display_roles:
                - IS_SUPER_USER   
        admin_locales:
            text_key: 'ADMIN_LOCALES'
            pattern: '/super/locales/0/20'
            display_roles:
                - IS_SUPER_USER   
  
  #messaging
admin_messaging:
    text_key: 'ADMIN_MESSAGING'
    pattern: '/super/messaging/0/20'
    display_roles:
        - IS_SUPER_USER  
    children:
        admin_discussiontypes:
            text_key: 'ADMIN_DISCUSSION_TYPES'
            pattern: '/super/departments/0/20'
            display_roles:
                - IS_SUPER_USER   
        admin_messagingtypes:
            text_key: 'ADMIN_MESSAGING_TYPES'
            pattern: '/super/messaging/types/0/20'
            display_roles:
                - IS_SUPER_USER  
        admin_notification_settings_types:
            text_key: 'ADMIN_NOTIFICATION_SETTINGS_TYPES'
            pattern: '/super/notifications/settings/0/20'
            display_roles:
                - IS_SUPER_USER    
        admin_notification_templates:
            text_key: 'ADMIN_NOTIFICATION_TEMPLATES'
            pattern: '/super/notifications/templates/0/20'
            display_roles:
                - IS_SUPER_USER     
        
#feedback
admin_feedback:
    text_key: 'ADMIN_FEEDBACK'
    pattern: '/super/feedback/0/20'
    display_roles:
        - IS_SUPER_USER 
    children:
        feedback_contacttypes:
            text_key: 'ADMIN_FEEDBACK_CONTACT_TYPES'
            pattern: '/super/feedback/contacttypes/0/20'
            display_roles:
                - IS_SUPER_USER  
        feedback_statuses:
            text_key: 'ADMIN_FEEDBACK_STATUSES'
            pattern: '/super/feedback/statuses/0/20'
            display_roles:
                - IS_SUPER_USER   
        feedback_types:
            text_key: 'ADMIN_FEEDBACK_TYPES'
            pattern: '/super/feedback/types/0/20'
            display_roles:
                - IS_SUPER_USER   
                
#incidents
admin_incidents:
    text_key: 'ADMIN_INCIDENTS'
    pattern: '/super/incidents/0/20'
    display_roles:
        - IS_SUPER_USER  
    children:
        incident_types:
            text_key: 'ADMIN_INCIDENT_TYPES'
            pattern: '/super/incidents/types/0/20'
            display_roles:
                - IS_SUPER_USER   
        incident_NotificationLists:
            text_key: 'ADMIN_INCIDENT_NOTIFICATION_LISTS'
            pattern: '/super/incidents/lists/0/20'
            display_roles:
                - IS_SUPER_USER   
                
#inventory
admin_inventory:
    text_key: 'ADMIN_INVENTORY'
    pattern: '/super/inventory/0/20'
    display_roles:
        - IS_SUPER_USER 
    children:
        admin_inventory_package_types:
            text_key: 'ADMIN_PACKAGE_TYPES'
            pattern: '/super/inventory/packagetypes/0/20'
            display_roles:
                - IS_SUPER_USER 

        admin_inventory_categories:
            text_key: 'ADMIN_INVENTORY_CATEGORIES'
            pattern: '/super/inventory/categories/0/20'
            display_roles:
                - IS_SUPER_USER 

        admin_inventory_types:
            text_key: 'ADMIN_INVENTORY_TYPES'
            pattern: '/super/inventory/types/0/20'
            display_roles:
                - IS_SUPER_USER 

                
                
#security 
admin_security:
    text_key: 'ADMIN_SECURITY'
    pattern: '#'
    display_roles:
        - IS_SUPER_USER  
    children:
        staff_roles:
            text_key: 'ADMIN_STAFF_ROLES'
            pattern: '/super/staff/roles/0/20'
            display_roles:
                - IS_SUPER_USER   
        contact_roles:
            text_key: 'ADMIN_CONTACT_ROLES'
            pattern: '/super/contacts/roles/0/20'
            display_roles:
                - IS_SUPER_USER     
        customer_roles:
            text_key: 'ADMIN_CUSTOMER_ROLES'
            pattern: '/super/customers/roles/0/20'
            display_roles:
                - IS_SUPER_USER    
                
#scoping
admin_scoping:
    text_key: 'ADMIN_SCOPING'
    pattern: '#'
    display_roles:
        - IS_SUPER_USER  
    children:
        room_types:
            text_key: 'ADMIN_ROOM_TYPES'
            pattern: '/super/scoping/roomtypes/0/20'
            display_roles:
                - IS_SUPER_USER   
        sections:
            text_key: 'ADMIN_SCOPING_SECTIONS'
            pattern: '/super/scoping/sections/0/20'
            display_roles:
                - IS_SUPER_USER 

#warehouse
admin_scoping:
    text_key: 'ADMIN_WAREHOUSE'
    pattern: '#'
    display_roles:
        - IS_SUPER_USER  
    children:
        warehouse_locations:
            text_key: 'WAREHOUSE_LOCATIONS'
            pattern: '/super/inventory/locations/0/20'
            display_roles:
                - IS_SUPER_USER   
        vehicles:
            text_key: 'ADMIN_VEHICLES'
            pattern: '/super/vehicles/0/20'
            display_roles:
                - IS_SUPER_USER 
                

#events
admin_events:
    text_key: 'ADMIN_EVENTS'
    pattern: '#'
    display_roles:
        - IS_SUPER_USER  
    children:
        event_types:
            text_key: 'ADMIN_EVENT_TYPES'
            pattern: '/super/events/eventtypes/0/20'
            display_roles:
                - IS_SUPER_USER           
                
#warehouse
admin_tickets:
    text_key: 'ADMIN_TICKETS'
    pattern: '#'
    display_roles:
        - IS_SUPER_USER  
    children:
        ticket_statuses:
            text_key: 'TICKET_STATUSES'
            pattern: '/super/tickets/statuses/0/20'
            display_roles:
                - IS_SUPER_USER   
        ticket_types:
            text_key: 'TICKET_TYPES'
            pattern: '/super/tickets/types/0/20'
            display_roles:
                - IS_SUPER_USER  
        ticket_priorities:
            text_key: 'TICKET_PRIORITIES'
            pattern: '/super/tickets/priorities/0/20'
            display_roles:
                - IS_SUPER_USER  
        ticket_resolutions:
            text_key: 'TICKET_RESOLUTIONS'
            pattern: '/super/tickets/resolutions/0/20'
            display_roles:
                - IS_SUPER_USER 
        ticket_actions:
            text_key: 'TICKET_ACTIONS'
            pattern: '/super/tickets/actions/0/20'
            display_roles:
                - IS_SUPER_USER  
        ticket_categories:
            text_key: 'TICKET_CATEGORIES'
            pattern: '/super/tickets/categories/0/20'
            display_roles:
                - IS_SUPER_USER                 