
# USER CONTEXT MENU - DROPDOWN ON THE RIGHT
admin_home:
    text_key: 'ADMIN_HOME'
    pattern: '/admin/home'
    section: usermenu
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF

super_user_home:
    text_key: 'SUPER_USER_HOME'
    pattern: '/super/home'
    section: usermenu
    display_roles:
        - IS_SUPER_USER
    children:
        admin_workperformed:
            active: true
            text_key: 'ADMIN_WORKPERFORMED'
            pattern: '/admin/workperformed/0/20'
            display_roles:
              - IS_ADMINISTRATOR
              - IS_PROJECT_MANAGER
              - IS_PM_ASSISTANT
              - IS_ACCOUNTING

admin_contactus:
    text_key: 'ADMIN_CONTACTUS'
    pattern: '/admin/contact/0/20'
    section: usermenu
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF

admin_notifications:
    active: true
    text_key: 'ADMIN_NOTIFICATIONS'
    pattern: '/admin/notifications/0/20'
    section: usermenu
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF

admin_messages:
    active: true
    text_key: 'ADMIN_MESSAGES'
    pattern: '/admin/messaging/0/20'
    section: usermenu
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
    children:
        messages_listall:
            text_key: 'ADMIN_MESSAGES_LIST_ALL'
            pattern: '/admin/messages/0/20'
            display_roles:
                - IS_STAFF

admin_reminders:
    active: true
    text_key: 'ADMIN_REMINDERS'
    pattern: '/admin/reminders/0/20'
    section: usermenu
    display_roles:
        - IS_STAFF


admin_cms:
    active: true
    text_key: 'ADMIN_CMS'
    pattern: '/admin/cms/pages/0/20'
    section: usermenu
    display_roles:
        - IS_ADMINISTRATOR
        - IS_EDITOR
    children:
        admin_cms_list_all:
            active: true
            text_key: 'ADMIN_CMS_LIST_ALL_PAGES'
            pattern: '/admin/cms/pages/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
        admin_cms_add_new:
            active: true
            text_key: 'ADMIN_CMS_ADD_NEW_PAGE'
            pattern: '/admin/cms/pages/0'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
        admin_cms_list_all_sections:
            active: true
            text_key: 'ADMIN_CMS_LIST_ALL_SECTIONS'
            pattern: '/admin/cms/sections/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
        admin_cms_list_all_blogs:
            active: true
            text_key: 'ADMIN_CMS_LIST_ALL_BLOGS'
            pattern: '/admin/cms/blogs/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
        admin_cms_add_new_blog:
            active: true
            text_key: 'ADMIN_CMS_ADD_NEW_BLOGS'
            pattern: '/admin/cms/blogs/0'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR

admin_events:
    active: true
    text_key: 'ADMIN_EVENTS'
    pattern: '/admin/events/0/20'
    section: usermenu
    display_roles:
        - IS_ADMINISTRATOR
        - IS_EDITOR
        - IS_STAFF
    children:
        events_list_all:
            active: true
            text_key: 'ADMIN_EVENTS_LIST_ALL'
            pattern: '/admin/events/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
                - IS_STAFF
        events_list_all_locations:
            active: true
            text_key: 'ADMIN_EVENTS_LIST_ALL_LOCATIONS'
            pattern: '/admin/events/locations/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
                - IS_STAFF
        events_list_all_contacts:
            active: true
            text_key: 'ADMIN_EVENTS_LIST_ALL_CONTACTS'
            pattern: '/admin/events/eventcontacts/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
                - IS_STAFF
        events_list_all_prospects:
            active: true
            text_key: 'ADMIN_EVENTS_LIST_ALL_PROSPECTS'
            pattern: '/admin/events/eventprospects/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
                - IS_STAFF
        events_list_all_prospects:
            active: true
            text_key: 'ADMIN_EVENTS_LIST_ALL_INVITE_LISTS'
            pattern: '/admin/events/lists/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
                - IS_STAFF

admin_call_matrix:
    active: false
    text_key: 'ADMIN_CALL_MATRIX'
    pattern: '/admin/callmatrix/0/14'
    section: 'usermenu'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_PROJECT_MANAGER
        - IS_PM_ASSISTANT




# MAIN NAVIGATION - ADMIN SECTION

admin_accounting:
    active: false
    text_key: 'ADMIN_ACCOUNTING'
    pattern: '/admin/accounting'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_PROJECT_MANAGER
        - IS_PM_ASSISTANT
        - IS_ACCOUNTING

admin_contents:
    active: false
    text_key: 'ADMIN_CONTENTS'
    pattern: '/admin/contents/jobs/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF

customer_service:
    text_key: 'CUSTOMER_SERVICE'
    display_roles:
        - IS_STAFF
    children:
        admin_incidents:
            active: true
            text_key: 'ADMIN_INCIDENTS'
            pattern: '/admin/incidents/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
            children:
                incidents_list_all:
                    active: true
                    text_key: 'ADMIN_INCIDENTS_LIST_ALL'
                    pattern: '/admin/incidents/0/20'
                    display_roles:
                        - IS_STAFF
        admin_deficiencies:
            active: false
            text_key: 'ADMIN_DEFICIENCIES'
            pattern: '/admin/deficiencies/0/20'
            display_roles:
                - IS_ADMINISTRATOR

directory:
    text_key: 'DIRECTORY'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
    children:
        admin_contacts:
            text_key: 'ADMIN_CONTACTS'
            pattern: '/admin/contacts/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_STAFF
            children:
                contacts_list_all:
                    text_key: 'ADMIN_CONTACTS_LIST_ALL'
                    pattern: '/admin/contacts/0/20'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_STAFF
                        - IS_PROJECT_MANAGER
                contacts_add_new:
                    text_key: 'ADMIN_CONTACTS_ADD_NEW'
                    pattern: '/admin/contacts/0'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_STAFF
                        - IS_PROJECT_MANAGER
                        - IS_PMA
                contacts_companies_listall:
                    text_key: 'ADMIN_COMPANIES_LIST_ALL'
                    pattern: '/admin/companies'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_STAFF
                        - IS_PROJECT_MANAGER
                        - IS_PMA
                contacts_add_new_company:
                    text_key: 'ADMIN_COMPANIES_ADD_NEW'
                    pattern: '/admin/companies/0'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_STAFF
                        - IS_PROJECT_MANAGER
                        - IS_PMA
        admin_claims:
            text_key: 'ADMIN_CLAIMS'
            pattern: '/admin/claims/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_ADMIN
                - IS_STAFF
            children:
                claims_list_all:
                    text_key: 'ADMIN_CLAIMS_LIST_ALL'
                    pattern: '/admin/claims/0/20'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_STAFF
                        - IS_PROJECT_MANAGER
                claims_create_new:
                    text_key: 'ADMIN_CLAIMS_CREATE_NEW'
                    pattern: '/admin/claim/1/0'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_PROJECT_MANAGER
                        - IS_PMA
                        - IS_PROJECT_MANAGER
                claims_scheduling:
                    text_key: 'ADMIN_CLAIMS_SCHEDULING'
                    pattern: '/admin/claims/scheduling/0/20'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_STAFF
                        - IS_PROJECT_MANAGER
                admin_keys:
                    active: false
                    text_key: 'ADMIN_KEYS'
                    pattern: '/admin/keys/0/20'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_STAFF

        admin_subcontractors:
            active: false
            text_key: 'ADMIN_SUBCONTRACTORS'
            pattern: '/admin/subcontractors/0/20'
            display_roles:
                - IS_ADMINISTRATOR
        admin_projects:
            active: true
            text_key: 'ADMIN_PROJECTS'
            pattern: '/admin/projects/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
                - IS_STAFF
            children:
                projects:
                    active: true
                    text_key: 'ADMIN_PROJECTS_LIST_ALL'
                    pattern: '/admin/projects/0/20'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_EDITOR
                        - IS_STAFF
                projects:
                    active: true
                    text_key: 'ADMIN_PROJECTS_CREATE_NEW'
                    pattern: '/admin/projects/0'
                    display_roles:
                        - IS_ADMINISTRATOR
                        - IS_EDITOR
                        - IS_STAFF

staff_list:
    text_key: 'ADMIN_STAFF'
    pattern: '#'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF
    children:
        staff_list:
            text_key: 'ADMIN_STAFF_LIST'
            pattern: '/admin/staff/0/20'
            display_roles:
                - IS_ADMIN
                - IS_ADMINISTRATOR
                - IS_STAFF
        staff_add_new:
            text_key: 'ADMIN_STAFF_ADD_NEW'
            pattern: '/admin/staff/0'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_HR_MANAGER


admin_scoping:
    text_key: 'ADMIN_SCOPING'
    pattern: '/admin/scoping/requests/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_SCOPER
        - IS_PROJECT_MANAGER
    children:
        scoping_list_all:
            text_key: 'ADMIN_SCOPING_LIST_ALL'
            pattern: '/admin/scoping/requests/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_SCOPER
                - IS_PROJECT_MANAGER
        scoping_takeoffs_list_all:
            text_key: 'ADMIN_SCOPING_TAKEOFFS_LIST_ALL'
            pattern: '/admin/scoping/takeoffs/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_SCOPER
                - IS_PROJECT_MANAGER

samples_list:
    text_key: 'ADMIN_SAMPLES'
    pattern: '/admin/samples/0/20'
    display_roles:
        - IS_ADMIN
        - IS_ADMINISTRATOR
        - IS_STAFF

admin_inventory:
    active: false
    text_key: 'ADMIN_INVENTORY'
    pattern: '#'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF
    children:
        admin_inventory_materials:
            text_key: 'ADMIN_INVENTORY_MATERIALS'
            pattern: '/admin/inventory/materials/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_STAFF

        admin_inventory_equipment:
            text_key: 'ADMIN_INVENTORY_EQUIPMENT'
            pattern: '/admin/inventory/equipment/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_STAFF


admin_satisfaction:
    active: false
    text_key: 'ADMIN_SATISFACTION'
    pattern: '/admin/satisfaction'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_PROJECT_MANAGER
        - IS_PM_ASSISTANT

admin_environmental:
    active: true
    text_key: 'ADMIN_ENVIRONMENTAL'
    pattern: '/admin/environmental/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_STAFF

admin_surveys:
    active: true
    text_key: 'ADMIN_SURVEYS'
    pattern: '/admin/surveys/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_EDITOR
    children:
        surveys_list_all:
            active: true
            text_key: 'ADMIN_SURVEYS_LIST_ALL'
            pattern: '/admin/surveys/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
        surveys_list_pages:
            active: true
            text_key: 'ADMIN_SURVEYS_LIST_ALL_PAGES'
            pattern: '/admin/surveys/pages/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
        surveys_list_panes:
            active: true
            text_key: 'ADMIN_SURVEYS_LIST_ALL_PANES'
            pattern: '/admin/surveys/panes/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
        surveys_list_questions:
            active: true
            text_key: 'ADMIN_SURVEYS_LIST_ALL_QUESTIONS'
            pattern: '/admin/surveys/questions/list/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR
        surveys_list_answers:
            active: true
            text_key: 'ADMIN_SURVEYS_LIST_ALL_ANSWERS'
            pattern: '/admin/surveys/answers/list/0/20'
            display_roles:
                - IS_ADMINISTRATOR
                - IS_EDITOR

admin_cart:
    active: false
    text_key: 'ADMIN_CART'
    pattern: '/admin/cart/sales/0/20'
    display_roles:
        - IS_ADMINISTRATOR
        - IS_EDITOR
        - IS_STAFF

#-------------------CLIENT PORTAL SECTION--------------------


portal_contacts_list:
    active: true
    text_key: 'PORTAL_CONTACTS_LIST'
    pattern: '/portal/contacts/list/0/20'
    display_roles:
        - IS_PORTAL_MANAGER


portal_projects_list:
    active: true
    text_key: 'PORTAL_PROJECTS_LIST'
    pattern: '/portal/projects/company'
    display_roles:
        - IS_PORTAL_MANAGER


portal_events_list:
    active: true
    text_key: 'PORTAL_EVENTS_LIST'
    pattern: '/portal/events/0/20'
    display_roles:
        - IS_PORTAL_MANAGER


#--------------------------main website ----------------------

website_services:
    active: true
    text_key: 'WEBSITE_SERVICES'
    pattern: '/restoration/services'
    display_roles:
        - IS_ANONYMOUS
        - IS_CUSTOMER

website_login:
    active: true
    text_key: 'WEBSITE_LOGIN'
    pattern: '/portal/entrance'
    display_roles:
        - IS_ANONYMOUS
        - IS_CUSTOMER


website_blogs_list:
    active: true
    text_key: 'WEBSITE_BLOGS_LIST'
    pattern: '/blogs/0/20'
    display_roles:
        - IS_ANONYMOUS
        - IS_CUSTOMER

website_contact:
    active: true
    text_key: 'WEBSITE_CONTACT'
    pattern: '/contact/contactus'
    display_roles:
        - IS_ANONYMOUS
        - IS_CUSTOMER

website_faqs:
    active: true
    text_key: 'WEBSITE_FAQS'
    pattern: '/restoration/frequently-asked-restoration-questions'
    display_roles:
        - IS_ANONYMOUS
        - IS_CUSTOMER

website_about:
    active: true
    text_key: 'WEBSITE_ABOUT'
    pattern: '/restoration/about-phoenix-restorations'
    display_roles:
        - IS_ANONYMOUS
        - IS_CUSTOMER
