
locale:
    component: "app/framework/core/components/locales/config/routing.yml"

    
locales:
    component: "app/framework/core/components/locales/config/routing.yml"

widgets:
    component: "app/framework/core/components/widgets/config/routing.yml"
  
render:
    component: "app/framework/core/components/render/config/routing.yml" 
  
    
basicmenu:
    component: "app/framework/core/components/basicmenu/config/routing.yml"

tabbedview:
    component: "app/framework/core/components/tabbedview/config/routing.yml"
    
users:
    component: "src/components/users/config/routing.yml"
 
   
home:
    component: "src/components/defaultItem/config/routing.yml"
    
    
fileuploads:
    component: "src/components/fileuploads/config/routing.yml"

cms:
    component: "app/framework/core/components/cms/config/routing.yml"
    


blogs:
    component: "app/framework/core/components/blogs/config/routing.yml"
    
cssmenu:
    component: "src/components/cssmenu/config/routing.yml"


    
#this is the default fallback to use if not found    
default:
    component: "src/components/cms/config/routing.yml"
    ymlkey: cms_view_page_1