

backoffice:
    component: "src/components/backoffice/config/routing.yml"


locale:
    component: "app/framework/core/components/locales/config/routing.yml"
locales:
    component: "app/framework/core/components/locales/config/routing.yml"


member:
    component: "src/components/members/config/routing.yml"
members:
    component: "src/components/members/config/routing.yml"
memberpreferences:
    component: "src/components/members/config/routing.yml"
member_reports:
    component: "src/components/members/config/routing.yml"
promote:
    component: "src/components/members/config/routing.yml"
memberSales:
    component: "src/components/members/config/routing.yml"

reports:
    component: "src/components/reports/config/routing.yml"

 
receiptDetails:
    component: "src/components/receipts/config/routing.yml"
receipt:
    component: "src/components/receipts/config/routing.yml"
receiptComments:
    component: "src/components/receipts/config/routing.yml"


invoicing:
    component: "src/components/invoicing/config/routing.yml"
fetchInvoice:
    component: "src/components/invoicing/config/routing.yml"
renewal:
    component: "src/components/invoicing/config/routing.yml"



valid_postalcode:
    component: "src/extensions/postalcodes/config/routing.yml"
valid_zipcode:
    component: "src/extensions/postalcodes/config/routing.yml"

#-------------------extensions-----------------


#------------------end extensions--------------



#this is the default fallback to use if not found    
default:
    component: "src/components/cms/config/routing.yml"
    ymlkey: cms_view_page_1