
'simple_auth': 
    'handler': 'core\components\security\handlers\AuthenticationHandler'
    #3 is the local db conn wrapped in a connection adapter
    'datasource': 'datasource3'
    'arguments': 
        security_context: '@security_context'
        authentication_manager: '@authentication_manager'
        
'login_auth': 
    'handler': 'core\components\security\handlers\AuthenticationHandler'
    'datasource': 'datasource3'
    'arguments': 
        security_context: '@security_context'
        authentication_manager: '@authentication_userlogin_manager'
        
 
'staff_login_auth': 
    'handler': 'core\components\security\handlers\AuthenticationHandler'
    'datasource': 'datasource4'
    'arguments': 
        security_context: '@security_context'
        authentication_manager: '@authentication_stafflogin_manager'    
        
 
'user_login_auth': 
    'handler': 'core\components\security\handlers\AuthenticationHandler'
    'datasource': 'datasource4'
    'arguments': 
        security_context: '@security_context'
        authentication_manager: '@authentication_userlogin_manager'      
     
     
contact_login_auth:
    'handler': 'core\components\security\handlers\AuthenticationHandler'
    'datasource': 'datasource4'
    'arguments': 
        security_context: '@security_context'
        authentication_manager: '@authentication_contactlogin_manager'
    
    
invite_login_auth:
    'handler': 'core\components\security\handlers\AuthenticationHandler'
    #4 is the rest datasource but it's wrapped in a connection adapter
    'datasource': 'datasource4' 
    'arguments': 
        security_context: '@security_context'
        authentication_manager: '@authentication_invitelogin_manager'

