
'simple_auth': 
    'handler': 'core\components\security\handlers\AuthenticationHandler'
    'datasource': 'datasource3'
    'arguments': 
        security_context: '@security_context'
        authentication_manager: '@authentication_manager'
        
'login_auth': 
    'handler': 'core\components\security\handlers\AuthenticationHandler'
    'datasource': 'datasource3'
    'arguments': 
        security_context: '@security_context'
        authentication_manager: '@authentication_userlogin_manager'   
     