

#------------------------ vehicle tolls -----------------



admin_vehiclestolls_list:
    pattern: admin/vehicles/tolls/*
    listeners:
        - { 'event': 'request_start', 'listener': 'components\vehicles\listeners\LoadVehicleTollsListener', 'datasource': 'datasource1', responseKey: VehicleTolls}
    defaults:
        component: components\vehicles\VehiclesComponent
        controller: components\vehicles\controllers\VehicleTollsController
        model: components\vehicles\models\VehicleTollModel
        method: listTolls
        view: core\views\JSONView
        viewKey: admin_vehiclestolls_list
        datasource: datasource1
                


#----------------------- vehicle types ---------------------                



admin_vehicletypes_edit:
    pattern: admin/vehicles/types/*

    defaults:
        component: components\vehicles\VehiclesComponent
        controller: components\vehicles\controllers\VehicleTypesController
        model: components\vehicles\models\VehicleTypeModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_vehicles_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/vehicles/locales/*/Navigation'  
    methods: [GET]
        
        
admin_vehicles_save:
    pattern: admin/vehicles/types/*
    listeners:
        - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel', 'cacheKey': 'ContactTypes'}
    defaults:
        component: components\vehicles\VehiclesComponent
        controller: components\vehicles\controllers\VehicleTypesController
        model: components\vehicles\models\VehicleTypeModel
        method: save
        view: core\views\TemplateView
        viewKey: admin_vehicles_save
        datasource: datasource1
        langFiles: 
            - 'src/components/vehicles/locales/*/Navigation'  
    methods: [POST]
        

admin_vehicles_list:
    pattern: admin/vehicles/types/*/*

    defaults:
        component: components\vehicles\VehiclesComponent
        controller: components\vehicles\controllers\VehicleTypesController
        model: components\vehicles\models\VehicleTypeModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_vehicles_list
        datasource: datasource1
        langFiles: 
            - 'src/components/vehicles/locales/*/Navigation'
                
                

#-------------------------- vehicles ------------
    

admin_vehicles_edit:
    pattern: admin/vehicles/*

    defaults:
        component: components\vehicles\VehiclesComponent
        controller: components\vehicles\controllers\VehiclesController
        model: components\vehicles\models\VehicleModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_vehicles_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/vehicles/locales/*/Navigation'  
    methods: [GET]
        
        
admin_vehicles_save:
    pattern: admin/vehicles/*
    listeners:
        - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel', 'cacheKey': 'ContactTypes'}
    defaults:
        component: components\vehicles\VehiclesComponent
        controller: components\vehicles\controllers\VehiclesController
        model: components\vehicles\models\VehicleModel
        method: save
        view: core\views\TemplateView
        viewKey: admin_vehicles_save
        datasource: datasource1
        langFiles: 
            - 'src/components/vehicles/locales/*/Navigation'  
    methods: [POST]
        

admin_vehicles_list:
    pattern: admin/vehicles/*/*

    defaults:
        component: components\vehicles\VehiclesComponent
        controller: components\vehicles\controllers\VehiclesController
        model: components\vehicles\models\VehicleModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_vehicles_list
        datasource: datasource1
        langFiles: 
            - 'src/components/vehicles/locales/*/Navigation'
                
      
        
      