

super_tickets_categories_list:
    category: utf8
    
super_tickets_categories_save:
    category: utf8
    
super_tickets_categories_edit:
    category: utf8
    
admin_tickets_edit:
    category: utf8
    phase: utf8
    
admin_tickets_edit:
    category: utf8
    phase: utf8
    action: utf8
    category: utf8
    department: utf8
    type: utf8
    

admin_tickets_list:
    category: utf8    
    
    