
admin_tickets_change_assignee:
    pattern: admin/tickets/changeassignee/*
    methods: [POST]    
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketsController
        model: components\tickets\models\TicketModel
        method: changeAssignedStaff
        view: core\views\JSONView
        viewKey: admin_tickets_change_assignee
        datasource: datasource1
 
admin_tickets_save:
    pattern: admin/tickets/*
    methods: [POST]
      
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketsController
        model: components\tickets\models\TicketModel
        method: save
        view: core\views\JSONView
        viewKey: admin_tickets_save
        datasource: datasource1            
            
admin_tickets_edit:
    pattern: admin/tickets/*
    methods: [GET]
    listeners:
        - { 'event': 'request_start', 'listener': 'components\tickets\listeners\LoadTicketCommentsListener', 'datasource': 'datasource1'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\departments\models\DepartmentModel', 'cacheKey': 'Departments' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimPhaseModel', 'cacheKey': 'ClaimPhases' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\tickets\models\TicketCategoryModel', 'cacheKey': 'TicketCategorys' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\tickets\models\TicketTypeModel', 'cacheKey': 'TicketTypes' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\tickets\models\TicketPriorityModel', 'cacheKey': 'TicketPrioritys' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\workperformed\models\WorkPerformedModel', 'cacheKey': 'ActionPerformeds' }
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketsController
        model: components\tickets\models\TicketModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_tickets_edit
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation' 

admin_tickets_list:
    pattern: admin/tickets/*/*
    methods: [GET]
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\tickets\models\TicketTypeModel', 'cacheKey': 'TicketTypes' }
        
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketsController
        model: components\tickets\models\TicketModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_tickets_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
      
            
#------------------------ status --------------------------------            
super_ticket_statuses_list:  
    pattern: super/tickets/statuses/*/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketStatusesController
        model: components\tickets\models\TicketStatusModel
        method: listall
        view: core\views\TemplateView
        viewKey: super_ticket_statuses_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'      
            
super_ticket_statuses_edit:  
    pattern: super/tickets/statuses/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketStatusesController
        model: components\tickets\models\TicketStatusModel
        method: edit
        view: core\views\JSONView
        viewKey: super_ticket_statuses_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'    
            
super_ticket_statuses_save:
    pattern: super/tickets/statuses/*
    listeners:
        - { 'event': 'save_success', 'listener': 'core\eventlisteners\DeleteCacheFileListener', 'datasource': 'datasource1' }
    
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketStatusesController
        model: components\tickets\models\TicketStatusModel
        method: save
        view: core\views\JSONView
        viewKey: super_ticket_statuses_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [POST]   
    
super_ticket_statuses_remove:
    pattern: super/tickets/statuses/remove/*
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketStatusesController
        model: components\tickets\models\TicketStatusModel
        method: setInactive
        view: core\views\JSONView
        viewKey: super_ticket_statuses_remove
        datasource: datasource1
    methods: [POST]
    
    
#----------------------------- types ---------------------
super_tickets_types_list:  
    pattern: super/tickets/types/*/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketTypesController
        model: components\tickets\models\TicketPriorityModel
        method: listall
        view: core\views\TemplateView
        viewKey: super_tickets_types_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'      
            
super_tickets_types_edit:  
    pattern: super/tickets/types/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketTypesController
        model: components\tickets\models\TicketPriorityModel
        method: edit
        view: core\views\JSONView
        viewKey: super_tickets_types_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'    
            
super_tickets_types_save:
    pattern: super/tickets/types/*
    listeners:
        - { 'event': 'save_success', 'listener': 'core\eventlisteners\DeleteCacheFileListener', 'datasource': 'datasource1' }
    
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketTypesController
        model: components\tickets\models\TicketPriorityModel
        method: save
        view: core\views\JSONView
        viewKey: super_tickets_types_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [POST]   
    
super_tickets_types_remove:
    pattern: super/tickets/types/remove/*
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketTypesController
        model: components\tickets\models\TicketPriorityModel
        method: setInactive
        view: core\views\JSONView
        viewKey: super_tickets_types_remove
        datasource: datasource1
    methods: [POST]    
    
    
    
#------------------------- priorities ----------------------    
            
super_tickets_priorities_edit:  
    pattern: super/tickets/priorities/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketPrioritiesController
        model: components\tickets\models\TicketPriorityModel
        method: edit
        view: core\views\JSONView
        viewKey: super_tickets_priorities_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'    
            
super_tickets_priorities_save:
    pattern: super/tickets/priorities/*
    listeners:
        - { 'event': 'save_success', 'listener': 'core\eventlisteners\DeleteCacheFileListener', 'datasource': 'datasource1' }
    
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketPrioritiesController
        model: components\tickets\models\TicketPriorityModel
        method: save
        view: core\views\JSONView
        viewKey: super_tickets_priorities_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [POST]   
    
super_tickets_priorities_remove:
    pattern: super/tickets/priorities/remove/*
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketPrioritiesController
        model: components\tickets\models\TicketPriorityModel
        method: setInactive
        view: core\views\JSONView
        viewKey: super_tickets_priorities_remove
        datasource: datasource1
    methods: [POST]    
    
super_tickets_priorities_list:  
    pattern: super/tickets/priorities/*/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketPrioritiesController
        model: components\tickets\models\TicketPriorityModel
        method: listall
        view: core\views\TemplateView
        viewKey: super_tickets_priorities_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'   
            
#-------------------- resolutions -----------------------------
   
            
super_tickets_resolutions_edit:  
    pattern: super/tickets/resolutions/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketResolutionsController
        model: components\tickets\models\TicketResolutionModel
        method: edit
        view: core\views\JSONView
        viewKey: super_tickets_resolutions_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'    
            
super_tickets_resolutions_save:
    pattern: super/tickets/resolutions/*
    listeners:
        - { 'event': 'save_success', 'listener': 'core\eventlisteners\DeleteCacheFileListener', 'datasource': 'datasource1' }
    
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketResolutionsController
        model: components\tickets\models\TicketResolutionModel
        method: save
        view: core\views\JSONView
        viewKey: super_tickets_resolutions_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [POST]   
    
super_tickets_resolutions_remove:
    pattern: super/tickets/resolutions/remove/*
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketResolutionsController
        model: components\tickets\models\TicketResolutionModel
        method: setInactive
        view: core\views\JSONView
        viewKey: super_tickets_resolutions_remove
        datasource: datasource1
    methods: [POST]    
    
super_tickets_resolutions_list:  
    pattern: super/tickets/resolutions/*/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketResolutionsController
        model: components\tickets\models\TicketResolutionModel
        method: listall
        view: core\views\TemplateView
        viewKey: super_tickets_priorities_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'      
            
#------------------------ actions ------------------------

            
super_tickets_actions_edit:  
    pattern: super/tickets/actions/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketActionsController
        model: components\tickets\models\TicketActionModel
        method: edit
        view: core\views\JSONView
        viewKey: super_tickets_actions_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'    
            
super_tickets_actions_save:
    pattern: super/tickets/actions/*
    listeners:
        - { 'event': 'save_success', 'listener': 'core\eventlisteners\DeleteCacheFileListener', 'datasource': 'datasource1' }
    
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketActionsController
        model: components\tickets\models\TicketActionModel
        method: save
        view: core\views\JSONView
        viewKey: super_tickets_actions_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [POST]   
    
super_tickets_actions_remove:
    pattern: super/tickets/actions/remove/*
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketActionsController
        model: components\tickets\models\TicketActionModel
        method: setInactive
        view: core\views\JSONView
        viewKey: super_tickets_actions_remove
        datasource: datasource1
    methods: [POST]    
    
super_tickets_actions_list:  
    pattern: super/tickets/actions/*/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketActionsController
        model: components\tickets\models\TicketActionModel
        method: listall
        view: core\views\TemplateView
        viewKey: super_tickets_priorities_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'      
            
            
#------------------------ categories ------------------------

            
super_tickets_categories_edit:  
    pattern: super/tickets/categories/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketCategoriesController
        model: components\tickets\models\TicketCategoryModel
        method: edit
        view: core\views\JSONView
        viewKey: super_tickets_categories_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'    
            
super_tickets_categories_save:
    pattern: super/tickets/categories/*
    listeners:
        - { 'event': 'save_success', 'listener': 'core\eventlisteners\DeleteCacheFileListener', 'datasource': 'datasource1' }
    
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketCategoriesController
        model: components\tickets\models\TicketCategoryModel
        method: save
        view: core\views\JSONView
        viewKey: super_tickets_categories_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [POST]   
    
super_tickets_categories_remove:
    pattern: super/tickets/categories/remove/*
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketCategoriesController
        model: components\tickets\models\TicketCategoryModel
        method: setInactive
        view: core\views\JSONView
        viewKey: super_tickets_categories_remove
        datasource: datasource1
    methods: [POST]    
    
super_tickets_categories_list:  
    pattern: super/tickets/categories/*/*
    methods: [GET]
    defaults:
        component: components\tickets\TicketsComponent
        controller: components\tickets\controllers\TicketCategoriesController
        model: components\tickets\models\TicketCategoryModel
        method: listall
        view: core\views\TemplateView
        viewKey: super_tickets_priorities_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'                  