

portal_login:
    pattern: portal/entrance
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\LoginController
        model: components\users\models\UserModel
        method: login
        view: core\views\TemplateView
        viewKey: portal_login
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'
            - 'src/components/staff/locales/*/login'
    methods: [GET]     
    
portal_login_submit:
    pattern: portal/entrance
    listeners:
        - { 'event': 'login_password_mismatch', 'listener': 'components\users\listeners\PasswordMismatchListener', 'datasource': 'datasource1'}
        - { 'event': 'login_status_locked', 'listener': 'components\users\listeners\StatusLockedListener', 'datasource': 'datasource1'}
        - { 'event': 'login_success', 'listener': 'components\users\listeners\TimestampLoginSuccessListener', 'datasource': 'datasource1'}
       # - { 'event': 'login_status_not_active', 'listener': 'components\staff\listeners\StatusNotActiveListener', 'datasource': 'datasource1'}
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\LoginController
        model: components\users\models\UserModel
        method: login
        view: core\views\TemplateView
        viewKey: portal_login_submit
        datasource: datasource1
        langFiles: 
            - 'src/components/shoppingcart/locales/*/Navigation'
            - 'src/components/defaultItem/locales/*/Contact'
    methods: [POST]
    
    
    
    
    
    
    
    
    
    
    
# this is the legacy stuff - might not need it          
users_get:
    pattern: users/get/*
#    defaults: { _controller: UserComponent:User:2nd }
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\User
        model: components\users\models\User
        method: edit
        view: core\views\TemplateView
        viewKey: users_get
        datasource: datasource1
    methods: [POST]
    
users_list:
    pattern: users/list
    #defaults: { _controller: UserComponent:User:save }
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\User
        model: components\users\models\User
        method: listall
        view: core\views\TemplateView
        viewKey: users_list
        datasource: datasource1
    methods: [POST]
    
users_list2:
    pattern: users/list/*/*
    #defaults: { _controller: UserComponent:User:save }
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\User
        model: components\users\models\User
        method: listall
        view: core\views\TemplateView
        viewKey: users_list
        datasource: datasource1
    methods: [POST]

users_save:
    pattern:  /users/new
    defaults: { _controller: ProductBundle:Default:save }
    datasource: datasource1
    methods: [POST]
    
users_list_alpha_desc:
    pattern:  /users/listAlphaDesc
    defaults: { _controller: ProductBundle:Default:listAlphaDesc }   
    
    
users_list_alpha_asc:
    pattern:  /users/listAlphaAsc
    defaults: { _controller: ProductBundle:Default:listAlphaAsc }
    

admin_users_list:
    pattern: /admin/users/list
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\User
        model: components\users\models\User
        method: listall
        view: core\views\TemplateView
        viewKey: admin_users_list
        datasource: datasource1
    methods: [POST]   
    
admin_users_edit:
    pattern: /admin/users/edit/*
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\User
        model: components\users\models\User
        method: edit
        view: core\views\TemplateView
        viewKey: admin_users_edit
        datasource: datasource3
    methods: [POST]       
    
admin_login:
    pattern: admin/login
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\LoginController
        model: components\users\models\UserModel
        method: login
        view: core\views\TemplateView
        viewKey: admin_login
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'
            - 'src/components/defaultItem/locales/*/Contact'
    methods: [GET]     
    
admin_login_submit:
    pattern: admin/login
    listeners:
        - { 'event': 'login_password_mismatch', 'listener': 'components\users\listeners\PasswordMismatchListener', 'datasource': 'datasource3'}
        - { 'event': 'login_status_locked', 'listener': 'components\users\listeners\StatusLockedListener', 'datasource': 'datasource3'}
       # - { 'event': 'login_status_not_active', 'listener': 'components\users\listeners\StatusNotActiveListener', 'datasource': 'datasource3'}
    defaults:
        component: components\users\UsersComponent
        controller: components\users\controllers\LoginController
        model: components\users\models\UserModel
        method: login
        view: core\views\TemplateView
        viewKey: admin_login_submit
        datasource: datasource1
        langFiles: 
            - 'src/components/shoppingcart/locales/*/Navigation'
            - 'src/components/defaultItem/locales/*/Contact'
    methods: [POST]