

component_list:
    template: list.php
    sections: {"section1": "src/themes/default/templates/sections/header.php", "section2": "src/components/users/views/leftnav.php", "section3": "src/components/users/views/payload.php"}
    
users_list2:
    template: list.php
    sections: {"section1": "src/themes/default/templates/sections/header.php", "section2": "src/components/users/views/leftnav.php", "section3": "src/components/users/views/payload.php"}
 


users_list:
    template: test.php
    sections: {"section1": "src/themes/default/templates/sections/header.php", "section2": "src/components/users/views/leftnav.php", "section3": "src/components/users/views/payload.php"}
 
users_get:
    template: test.php
    sections: {"section1": "src/themes/default/templates/sections/header.php", "section2": "src/components/users/views/leftnav.php", "section3": "src/components/users/views/get.php"}
       
admin_login:
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/users/views/login/login-form.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
admin_login_submit:
    template: admin-list.php
    sections: 
        -
            "section1": "src/components/shoppingcart/views/admin/topnav.php"
            "section3": "src/components/users/views/login/welcome.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    