admin_blogs_save:
    subject: utf8
    comments: utf8
    permalink: utf8
    tags: utf8
    
admin_blogs_list:
    subject: utf8
    
admin_blogs_edit:  
    subject: utf8
    comments: utf8
    permalink: utf8
    tags: utf8  
    
website_blogs_list:
    subject: utf8
    permalink: utf8
    
website_blogs_view:  
    subject: utf8
    comments: utf8
    permalink: utf8
    tags: utf8
    
website_blogs_feed:   
    subject: utf8 
    permalink: utf8