#admin_login:
#    listeners:
#        -
#            event: 'request_end'
#            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
#            datasource: 'datasource1'
#            formBuilder: 'components\staff\form\LoginBuilder'
#            model: 'components\staff\models\StaffModel'
#            cacheKey: 'LoginForm'
#            formName: 'form'

admin_staff_edit_home:
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\StaffRoleModel', 'cacheKey': 'StaffRoles' }
       # - { 'event': 'request_start', 'listener': 'components\staff\listeners\LoadStaffAuthorizationsByIdListener', 'datasource': 'datasource1' }
       # - { 'event': 'request_start', 'listener': 'components\staff\listeners\LoadStaffRolesByIdListener', 'datasource': 'datasource1' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\departments\models\DepartmentModel', 'cacheKey': 'Departments'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\StaffPositionModel', 'cacheKey': 'StaffPositions'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\StaffTypeModel', 'cacheKey': 'StaffTypes'}
    
         #build the form for StaffAuthorization 
        -
            event: 'request_end'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\staff\form\StaffAuthorizationBuilder'
            model: 'components\staff\models\StaffAuthorizationModel'
            cacheKey: 'StaffAuthorizationForm'
            formName: 'aForm'
            dependencies:
                - { dependency: StaffAuthorization, model: StaffAuthorization }
        
        #build the form for Staff Roles/permissions
        -
            event: 'request_end'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\staff\form\StaffRoleBuilder'
            model: 'components\staff\models\StaffRoleModel'
            cacheKey: 'StaffRolesForm'
            formName: 'roleForm'
            dependencies:
                - { dependency: StaffRoles, model: StaffRole }
