

admin_staff_home:
    pattern: admin/staff
    listeners:
        - { 'event': 'request_start', 'listener': 'core\components\widgets\eventlisteners\LoadSystemWidgetsListener', 'datasource': 'datasource1', 'cacheKey': 'SystemWidgets'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\departments\models\DepartmentModel', 'cacheKey': 'Departments'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\StaffPositionModel', 'cacheKey': 'StaffPositions'}
    
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        method: index
        view: core\views\TemplateView
        viewKey: admin_staff_home
        datasource: datasource1
    methods: [GET] 
    
admin_staff_create_new:
    pattern: admin/staff/0  
    listeners:
        - { 'event': 'request_start', 'listener': 'core\components\widgets\eventlisteners\LoadSystemWidgetsListener', 'datasource': 'datasource1', 'cacheKey': 'SystemWidgets'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\StaffRoleModel', 'cacheKey': 'StaffRoles' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\departments\models\DepartmentModel', 'cacheKey': 'Departments'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\StaffPositionModel', 'cacheKey': 'StaffPositions'}
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        method: createNew
        view: core\views\TemplateView
        viewKey: admin_staff_create_new
        datasource: datasource1
    methods: [GET] 
    
admin_staff_edit_home:
    pattern: admin/staff/*  
    listeners:
        - { 'event': 'request_start', 'listener': 'core\components\widgets\eventlisteners\LoadSystemWidgetsListener', 'datasource': 'datasource1', 'cacheKey': 'SystemWidgets'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\StaffRoleModel', 'cacheKey': 'StaffRoles' }
        - { 'event': 'request_start', 'listener': 'components\staff\listeners\LoadStaffRolesByIdListener', 'datasource': 'datasource1' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\departments\models\DepartmentModel', 'cacheKey': 'Departments'}
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\StaffPositionModel', 'cacheKey': 'StaffPositions'}
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_staff_edit_home
        datasource: datasource1
    methods: [GET] 
    
admin_staff_rest_list:
    pattern: admin/staff/*/*    
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        method: listall
        view: core\views\JSONView
        viewKey: admin_staff_rest_list
        datasource: datasource1
    methods: [GET]     
    
admin_staff_rest_paginator:
    pattern: admin/staff/pagination/*/*
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        method: paginationJson
        view: core\views\JSONView
        viewKey: admin_staff_rest_paginator
        datasource: datasource1    