

admin_staff_edit_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "section2": "src/components/staff/views/admin/subnav.php"
            "content": "src/components/staff/views/admin/staff-edit.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - staffAdmin
    head:
        - @components/staff/dist/bower_components/angular/angular.min.js
        - @components/staff/dist/bower_components/jquery/dist/jquery.min.js
        - @components/staff/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/staff/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/bower_components/dropzone/dist/min/dropzone.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/staff/dist/js/staff.concat.js
        #- @components/staff/dist/js/staff.min.js
    css:
        - @components/staff/dist/css/staff.min.css
        - @extensions/angular/dist/bower_components/dropzone/dist/dropzone.css



admin_staff_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "context-button": "src/components/staff/views/admin/context-button.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/staff/views/admin/staff-list.php"
            "section2": "src/components/staff/views/admin/subnav.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - staffAdmin

    head:
        - @components/staff/dist/bower_components/angular/angular.min.js
        - @components/staff/dist/bower_components/jquery/dist/jquery.min.js
        - @components/staff/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/staff/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/staff/dist/js/staff.concat.js
        #- @components/staff/dist/js/staff.min.js
    css:
        - @components/staff/dist/css/staff.min.css



admin_staff_create_new:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "section2": "src/components/staff/views/admin/subnav.php"
            "section3": "src/components/staff/views/admin/create-new-wizard.php"
            "footer": "src/themes/default/templates/sections/footer.php"



#--------------------- Timesheet section -------------------------
admin_staff_timesheets:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "context-button": "src/components/staff/views/admin/context-button.php"
            "content": "src/components/staff/views/admin/timesheets/staffTimesheets.php"
            "section2": "src/components/staff/views/admin/subnav.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - staffAdmin
    head:
        - @components/staff/dist/bower_components/angular/angular.min.js
        - @components/staff/dist/bower_components/jquery/dist/jquery.min.js
        - @components/staff/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/staff/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @components/staff/dist/js/staff.concat.js
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
    css:
        - @components/staff/dist/css/staff.min.css



#--------------------- login section -------------------------
admin_login:
    template: list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section3": "src/components/staff/views/login/login-form.php"
            "section5": "src/themes/default/templates/sections/footer.php"
            "header": "src/themes/default/templates/sections/header.php"
#            "context-button": "src/components/staff/views/admin/context-button.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
#            "content": "src/components/staff/views/login/login-form.php"
#            "section2": "src/components/staff/views/admin/subnav.php"
#            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - staffAdmin
    head:
        - @components/staff/dist/bower_components/angular/angular.min.js
        - @components/staff/dist/bower_components/jquery/dist/jquery.min.js
        - @components/staff/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/staff/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @components/staff/dist/js/staff.concat.js
        - @extensions/angular/dist/js/angular-extension.concat.js
    css:
        - @components/staff/dist/css/staff.min.css

admin_login_reset:
    template: list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section3": "src/components/staff/views/login/reset.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    head:
    javascript:
    css:

        - @components/staff/dist/css/staff.min.css

admin_login_reset_submit:
    template: message.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section3": "src/components/staff/views/login/reset-complete.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    head:
    javascript:
    css:
        - @components/staff/dist/css/staff.min.css

admin_login_confirmreset:
    template: message.php
    sections:
        -
            "header": "src/themes/default/templates/sections/portal-header.php"
            "content": "src/components/staff/views/login/confirm-reset.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    head:
    javascript:
    css:
        - @components/staff/dist/css/staff.min.css


admin_login_confirmreset_submit:
    template: message.php
    sections:
        -
            "header": "src/themes/default/templates/sections/portal-header.php"
            "content": "src/components/staff/views/login/confirm-reset-complete.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    head:
    javascript:
    css:
        - @components/staff/dist/css/staff.min.css

admin_login_failed:
    template: message.php
    sections:
        -
            "header": "src/themes/default/templates/sections/portal-header.php"
            "content": "src/components/staff/views/login/failed.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    head:
    javascript:
    css:
        - @components/staff/dist/css/staff.min.css


admin_staff_timesheets_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/staff/views/admin/subnav.php"
            "content": "src/components/staff/views/admin/timesheets.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - staffAdmin
            - rootApp
    head:
        - @components/staff/dist/bower_components/angular/angular.min.js
        - @components/staff/dist/bower_components/jquery/dist/jquery.min.js
        - @components/staff/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/staff/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/bower_components/dropzone/dist/min/dropzone.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/staff/dist/js/staff.concat.js
        #- @components/staff/dist/js/staff.min.js
    css:
        - @components/staff/dist/css/staff.min.css
