


super_staff_roles_list:
    template: super-list.php
    sections: 
        -
            "section3": "src/components/staff/views/admin/roles/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_staff_edit:
    template: newsfeed.php
    sections: 
        -
           # "section1": "src/themes/default/templates/sections/admin-header.php"
           # "section2": "src/components/staff/views/admin/subnav.php"
            "section1": "src/components/staff/views/admin/staff-edit.php"
           # "section4": "src/themes/default/templates/sections/footer.php"

admin_staff_list:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/staff/views/admin/subnav.php"
            "section3": "src/components/staff/views/admin/staff-list.php"
            "featureslider-edit1": "src/components/staff/views/admin/edit.php"
            "featureslider-edit2": "src/components/staff/views/admin/edit2.php"
            "featureslider-edit3": "src/components/staff/views/admin/edit3.php"
            "featureslider-edit4": "src/components/staff/views/admin/edit4.php"
            "featureslider-edit5": "src/components/staff/views/admin/edit5.php"
            "section4": "src/themes/default/templates/sections/footer.php"
        
    
admin_login:
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/staff/views/login/login-form.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
admin_login_submit:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/defaultItem/views/admin/home.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_staff_edit_permissions_save:  
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/staff/views/admin/permissions.php"
            "section4": "src/themes/default/templates/sections/footer.php"  
    
    
admin_staff_permissions_get:  
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/staff/views/admin/permissions.php" 
            
admin_staff_permissions_save:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/staff/views/admin/save-success.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_login_roles:    
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/staff/views/login/error.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
admin_staff_credentials_edit:   
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/staff/views/admin/credentials.php"        
            
admin_staff_emergencycontacts_list:    
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/staff/views/admin/emergencycontacts/list.php"
            
            
admin_staff_permissions_select:
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/staff/views/admin/permissions.php"
    
    
admin_login_failed:  
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/staff/views/admin/incorrect-password.php"
            "section4": "src/themes/default/templates/sections/footer.php"           
            
admin_status_locked:     
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/staff/views/admin/status-locked.php"
            "section4": "src/themes/default/templates/sections/footer.php"          

            
admin_staff_rest_edit: 
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/staff/views/admin/test.php"   