## YAML Template.
---


staff_list: 
    file: 'src/components/staff/views/admin/staff-list.php'
    head:
        - //ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js
        - //cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.0/ui-bootstrap-tpls.min.js
    javascript:
        - //ajax.googleapis.com/ajax/libs/angularjs/1.3.14/test.js
    css:
        
        
staff_edit_contact: 'src/components/staff/views/widgets/contact-info.php'

staff_edit_employment: 'src/components/staff/views/widgets/employment-info.php'

staff_general_info: 'src/components/staff/views/widgets/general-info.php'

staff_credentials: 'src/components/staff/views/widgets/credentials.php'

staff_emergency_contact_info: 'src/components/staff/views/widgets/emergency-contact-info.php'

staff_roles: 'src/components/staff/views/widgets/staff-roles.php'

staff_login: 'src/components/staff/views/widgets/staff-login.php'

staff_image_upload: 'src/components/staff/views/widgets/photo-upload.php'
