## YAML Template.
---


staff_list:
    file: 'src/components/staff/views/admin/staff-list.php'
    head:
        - @components/staff/dist/bower_components/angular/angular.min.js
        - @components/staff/dist/bower_components/jquery/dist/jquery.min.js
        - @components/staff/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/staff/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @components/staff/dist/js/staff.min.js
    css:
        - @components/staff/dist/css/staff.min.css

staff_edit_contact: 'src/components/staff/views/widgets/contact-info.php'

staff_edit_employment: 'src/components/staff/views/widgets/employment-info.php'

staff_general_info: 'src/components/staff/views/widgets/general-info.php'

staff_credentials: 'src/components/staff/views/widgets/credentials.php'

staff_emergency_contact_info: 'src/components/staff/views/widgets/emergency-contact-info.php'

staff_roles: 'src/components/staff/views/widgets/staff-roles.php'

staff_login:
    file: 'src/components/staff/views/widgets/staff-login.php'
    head:
        - src/components/staff/dist/bower_components/angular/angular.min.js
        - src/components/staff/dist/bower_components/jquery/dist/jquery.min.js
        - src/components/staff/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - src/components/staff/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - src/components/staff/dist/js/staff.min.js
    css:
        - src/components/staff/dist/css/staff.min.css

staff_image_upload: 'src/components/staff/views/widgets/photo-upload.php'
