admin_scoping_takeoffs_edit:
    listeners:
        - { 'cacheKey': 'Claims', 'class': 'components\claims\models\ClaimModel', 'event': 'request_start', 'listener': 'core\eventlisteners\LoadItemListener', 'datasource': 'datasource1' }
        #- { 'cacheKey': 'AreaTypes', 'class': 'components\claims\models\ClaimModel', 'event': 'request_start', 'listener': 'core\eventlisteners\LoadItemListener', 'datasource': 'datasource1' }
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\scoping\form\MaterialTakeOffBuilder'
            model: 'components\scoping\models\ScopeMaterialTakeoffModel'
            cacheKey: 'MaterialTakeoffForm'
            formName: 'form'
            dependencies:
                - { dependency: Claims, key: claims, value: id, text: title }
                #- { dependency: AreaTypes, key: areaTypes, value: id, text: title }


admin_scoping_takeoffs_edit_sheet:
    listeners:
        #- { 'cacheKey': 'Claims', 'class': 'components\claims\models\ClaimModel', 'event': 'request_start', 'listener': 'core\eventlisteners\LoadItemListener', 'datasource': 'datasource1' }
        -
            event: 'request_start'
            listener: 'core\components\render\eventlisteners\MultiFormBuilderListener'
            datasource: 'datasource1'
            formBuilder: 'components\scoping\form\MaterialTakeOffBuilder'
            model: 'components\scoping\models\ScopeMaterialTakeoffModel'
            cacheKey: 'MaterialTakeoffForm'
            formName: 'form'
            dependencies:
            #    - { dependency: Claims, key: claims, value: id, text: title }
    