


    

admin_scoperequest_edit:
    pattern: admin/scoping/requests/*

    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeRequestsController
        model: components\scoping\models\ScopeRequestModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_scoperequest_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  
    methods: [GET]
        
        
admin_scoperequest_save:
    pattern: admin/scoping/requests/*
    listeners:
        - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel', 'cacheKey': 'ContactTypes'}
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeRequestsController
        model: components\scoping\models\ScopeRequestModel
        method: save
        view: core\views\TemplateView
        viewKey: admin_scoperequest_save
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  
    methods: [POST]
        
admin_scoperequest_save_contact:
    pattern: admin/scoping/requests/contact/*
    listeners:
        - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel', 'cacheKey': 'ContactTypes'}
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeRequestsController
        model: components\scoping\models\ScopeRequestModel
        method: saveContact
        view: core\views\TemplateView
        viewKey: admin_scoperequest_save_contact
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  
    methods: [POST]
        
admin_scoperequest_edit_contact:
    pattern: admin/scoping/requests/contact/*
    listeners:
        - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel', 'cacheKey': 'ContactTypes'}
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeRequestsController
        model: components\scoping\models\ScopeRequestModel
        method: loadContact
        view: core\views\TemplateView
        viewKey: admin_scoperequest_edit_contact
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'      
 

admin_scoperequests_list:
    pattern: admin/scoping/requests/*/*

    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeRequestsController
        model: components\scoping\models\ScopeRequestModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_scoperequests_list
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'

# TAKEOFFS
admin_scoping_takeoffs_home:
    pattern: admin/scoping/takeoffs
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeMaterialTakeoffsController
        model: components\scoping\models\ScopeMaterialTakeoffModel
        method: index
        view: extensions\angular\views\AngularTemplateView
        viewKey: admin_scoping_takeoffs_home
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'
    method: [GET]
    staticCache: true

admin_scoping_takeoffs_save:
    pattern: admin/scoping/takeoffs/save/*
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeMaterialTakeoffsController
        model: components\scoping\models\ScopeMaterialTakeoffModel
        method: save
        view: core\views\JSONView
        viewKey: admin_scoping_takeoffs_save
        datasource: datasource1
        langFiles: 
    method: [POST]  

admin_scoping_takeoffs_edit_sheet:
    pattern: admin/scoping/takeoffs/*/*
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeMaterialTakeoffsController
        model: components\scoping\models\ScopeMaterialTakeoffModel
        method: editByLocation
        view: extensions\angular\views\AngularTemplateView
        viewKey: admin_scoping_takeoffs_edit_sheet
        datasource: datasource1
        langFiles: 
            - 'src/components/scoping/locales/*/Scoping'
            - 'app/locales/*/website'
    method: [GET]
    staticCache: true

admin_scoping_takeoffs_edit:
    pattern: admin/scoping/takeoffs/*
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeMaterialTakeoffsController
        model: components\scoping\models\ScopeMaterialTakeoffModel
        method: edit
        view: extensions\angular\views\AngularTemplateView
        viewKey: admin_scoping_takeoffs_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'
    method: [GET]
    staticCache: true
    
admin_scoping_takeoffs_get:
    pattern: admin/scoping/takeoffs/get/*/*
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeMaterialTakeoffsController
        model: components\scoping\models\ScopeMaterialTakeoffModel
        method: getByLocation
        view: core\views\JSONView
        viewKey: admin_scoping_takeoffs_get
        datasource: datasource1
    method: [GET] 
    
admin_scoping_edit:
    pattern: admin/scoping/*
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ClaimScopesController
        model: components\scoping\models\ClaimScopeModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_scoping_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation' 
            
      
admin_scoping_view:
    pattern: admin/scoping/view/*
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ClaimScopesController
        model: components\scoping\models\ClaimScopeModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_scoping_view
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'             
     
admin_scoping_location_edit:            
    pattern: admin/scoping/locations/*/*
    listeners:
       # - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadItemListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimModel'}
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ClaimScopesController
        model: components\claims\models\ClaimLocationModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_scoping_location_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'        
     
admin_scoping_location_rooms:            
    pattern: admin/scoping/location/rooms/*/*
    methods: [GET]
    listeners:
    #    - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadItemListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimModel'}
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ClaimScopesController
        model: components\claims\models\ClaimLocationModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_scoping_location_rooms
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  
            
admin_scoping_location_rooms_save:            
    pattern: admin/scoping/location/rooms/*/*
    methods: [POST]
    listeners:
    #    - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadItemListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimModel'}
    defaults:
        component: components\claims\ClaimsComponent
        controller: components\claims\controllers\ClaimLocationsController
        model: components\claims\models\ClaimLocationModel
        method: saveRoom
        view: core\views\TemplateView
        viewKey: admin_scoping_location_rooms_save
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'     
            
admin_scoping_location_takeoff:            
    pattern: admin/scoping/takeoff/*
    methods: [GET]
    listeners:
    #    - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadItemListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimModel'}
    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ScopeMaterialTakeoffsController
        model: components\scoping\models\ScopeMaterialTakeoffModel
        method: getTakeOff
        view: core\views\TemplateView
        viewKey: admin_scoping_location_takeoff
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'                


      
      
          #locationId, offset, limit
admin_scoping_rooms_list:
    pattern: admin/scoping/locations/rooms/*/*/*

    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ClaimScopeRoomsController
        model: components\scoping\models\ClaimScopeRoomModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_scoping_rooms_list
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'          
        
          
admin_scoping_home:
    pattern: admin/scoping/*/*

    defaults:
        component: components\scoping\ScopingComponent
        controller: components\scoping\controllers\ClaimScopesController
        model: components\scoping\models\ClaimScopeModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_scoping_home
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'                   