
failkey: admin_login
#admin_staff_edit
                
fields:
    - email:
        - 
            class: Required     
            failkey: VALIDATION_REQUIRED_FIELD
        -
            class: AlphaNumeric
            failkey: VALIDATION_INVALID_EMAIL
            params:
                - maxlength: 50 

    - password:
        - 
            class: Required      
            failkey: VALIDATION_REQUIRED_FIELD          
       

                