


failkey: floorplans_edit
#admin_staff_edit
                
fields:
    - name:
        - 
            class: Required      
            failkey: VALIDATION_REQUIRED_FIELD
        - 
            class: AlphaNumeric    
            failkey: VALIDATION_INVALID_ALPHANUMERIC
            params:
                maxlength: 50
                
                
    - foorPlan:
        - 
            class: Required      
            failkey: VALIDATION_REQUIRED_FIELD
       
                