


failkey: projectaddress_edit
#admin_staff_edit
                
fields:
    - buildingName:
        - 
            class: String    
            failkey: VALIDATION_INVALID_STRING
            params:
                maxlength: 50
                
                
    - address1:
        - 
            class: Required      
            failkey: VALIDATION_REQUIRED_FIELD
        - 
            class: Address    
            failkey: VALIDATION_INVALID_ADDRESS
            params:
                maxlength: 50
                
                
    - address2:
        - 
            class: Address    
            failkey: VALIDATION_INVALID_ADDRESS
            params:
                maxlength: 50
                
    - city:                
        - 
            class: Required      
            failkey: VALIDATION_REQUIRED_FIELD
        - 
            class: Address    
            failkey: VALIDATION_INVALID_CITY
            params:
                maxlength: 50
                
    - Provinces_id:                
        - 
            class: Required      
            failkey: VALIDATION_REQUIRED_FIELD
            

                
    - postalCode:                
        - 
            class: Required      
            failkey: VALIDATION_REQUIRED_FIELD
        - 
            class:  AlphaNumeric   
            failkey: VALIDATION_INVALID_POSTAL
            params:
                maxlength: 10  
               