
#locationId, sampleId
admin_samples_edit:
    pattern: admin/samples/edit/*

    defaults:
        component: components\samples\SamplesComponent
        controller: components\samples\controllers\SamplesController
        model: components\samples\models\SampleModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_samples_edit
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [GET]
 
 
admin_samples_list:
    pattern: admin/samples/*/*

    defaults:
        component: components\samples\SamplesComponent
        controller: components\samples\controllers\SamplesController
        model: components\samples\models\SampleModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_samples_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'  
    methods: [GET]

       