
admin_sections_create:
    pattern: admin/incidents/sections/*
    methods: [GET]
    defaults:
        component: components\incidents\IncidentsComponent
        controller: components\incidents\controllers\SectionsController
        model: components\incidents\models\SectionModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_sections_create
        datasource: datasource1   
    

admin_sections_save:
    pattern: admin/incidents/sections/*
    methods: [POST]
    defaults:
        component: components\incidents\IncidentsComponent
        controller: components\incidents\controllers\SectionsController
        model: components\incidents\models\SectionModel
        method: save
        view: core\views\TemplateView
        viewKey: admin_sections_save
        datasource: datasource1   
        
        
admin_sections_list:
    pattern: admin/incidents/sections/*/*
    methods: [GET]
    defaults:
        component: components\incidents\IncidentsComponent
        controller: components\incidents\controllers\SectionsController
        model: components\incidents\models\SectionModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_sections_list
        datasource: datasource1         
        
admin_incidenttypes_edit:
    pattern: admin/incidents/type/*
    methods: [GET]
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\incidents\models\SectionModel', 'cacheKey': 'Sections' }
    defaults:
        component: components\incidents\IncidentsComponent
        controller: components\incidents\controllers\IncidentTypesController
        model: components\incidents\models\IncidentTypeModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_incidenttypes_edit
        datasource: datasource1   
   
admin_incidenttypes_save:
    pattern: admin/incidents/type/*
    methods: [POST]
    defaults:
        component: components\incidents\IncidentsComponent
        controller: components\incidents\controllers\IncidentTypesController
        model: components\incidents\models\IncidentTypeModel
        method: save
        view: core\views\TemplateView
        viewKey: admin_incidenttypes_save
        datasource: datasource1   
        
                
admin_incidenttypes_list:
    pattern: admin/incidents/type/*/*
    defaults:
        component: components\incidents\IncidentsComponent
        controller: components\incidents\controllers\IncidentTypesController
        model: components\incidents\models\IncidentTypeModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_incidenttypes_list
        datasource: datasource1      
             
admin_incidents_create:
    pattern: admin/incidents/*
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\DepartmentModel', 'cacheKey': 'Departments' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\incidents\models\IncidentTypeModel', 'cacheKey': 'IncidentTypes' }
    defaults:
        component: components\incidents\IncidentsComponent
        controller: components\incidents\controllers\IncidentsController
        model: components\incidents\models\IncidentModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_incidents_list
        datasource: datasource1              
             
admin_incidents_list:
    pattern: admin/incidents/*/*
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\staff\models\DepartmentModel', 'cacheKey': 'Departments' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\incidents\models\IncidentTypeModel', 'cacheKey': 'IncidentTypes' }
    defaults:
        component: components\incidents\IncidentsComponent
        controller: components\incidents\controllers\IncidentsController
        model: components\incidents\models\IncidentModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_incidents_list
        datasource: datasource1      
                     