
datasource1:
    class: core\datasources\RestDataSource
    credentials: 
        baseUrl: http://192.168.56.102
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: serverIdTokenHere

datasource2:
    class: core\datasources\FileDataSource

