
datasource1:
    class: core\datasources\RestDataSource
    credentials: 
        baseUrl: http://192.168.1.109
        format: json
        headers:
            authorization: tokengoeshere
            serverAuth: bQd18aba1df45jk7858c8ae88a57fa30

datasource2:
    class: core\datasources\FileDataSource

