default:
    component: "components/defaultItem/config/routing.yml"
    
about:
    component: "components/defaultItem/config/routing.yml"
    
users:
    component: "components/users/config/routing.yml"
    
    
app:
    component: "components/users/config/routing.yml"
    

cart:
    component: "components/shoppingcart/config/routing.yml"


