

admin_companies_home:
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\companies\models\CompanyTypeModel', 'cacheKey': 'CompanyTypes' }
        -
             event: 'request_end'
             listener: 'core\components\render\eventlisteners\FormBuilderListener'
             datasource: 'datasource1'
             formBuilder: 'components\companies\form\CompanyBuilder'
             model: 'components\companies\models\CompanyModel'
             cacheKey: 'CompanySearchForm'
             dependencies:
                 - { dependency: CompanyTypes, key: companyTypes, value: id, text: type}