#------------ rest


admin_companies_rest_paginator:
    pattern: admin/companies/pagination/*/*
    defaults:
        component: components\companies\CompaniesComponent
        controller: components\companies\controllers\CompaniesController
        model: components\companies\models\CompanyModel
        method: pagination
        view: core\views\JSONView
        viewKey: admin_companies_rest_list
        datasource: datasource1
        
        
admin_companies_rest_list:
    pattern: admin/companies/rest/*/*
   # listeners:
   #     - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel'}
    defaults:
        component: components\companies\CompaniesComponent
        controller: components\companies\controllers\CompaniesController
        model: components\companies\models\CompanyModel
        method: backboneListall
        view: core\views\JSONView
        viewKey: admin_companies_rest_list
        datasource: datasource1



#------------ end rest









admin_companies_search:
    pattern: admin/companies/search
   # listeners:
   #     - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel'}
    defaults:
        component: components\companies\CompaniesComponent
        controller: components\companies\controllers\CompaniesController
        model: components\companies\models\CompanyModel
        method: search
        view: core\views\JSONView
        viewKey: admin_companies_search
        datasource: datasource1

admin_companies_view:
    pattern: admin/companies/view/*
   # listeners:
   #     - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel'}
    defaults:
        component: components\companies\CompaniesComponent
        controller: components\companies\controllers\CompaniesController
        model: components\companies\models\CompanyModel
        method: edit
        view: core\views\JSONView
        viewKey: admin_companies_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation' 
   
admin_companies_list:
    pattern: admin/companies/*/*
   # listeners:
   #     - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel'}
    defaults:
        component: components\companies\CompaniesComponent
        controller: components\companies\controllers\CompaniesController
        model: components\companies\models\CompanyModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_companies_list
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation' 
   
admin_companies_edit:
    pattern: admin/companies/*
    methods: [GET]
   # listeners:
   #     - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel'}
    defaults:
        component: components\companies\CompaniesComponent
        controller: components\companies\controllers\CompaniesController
        model: components\companies\models\CompanyModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_companies_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation' 
 

admin_companies_save:
    pattern: admin/companies/*
    methods: [POST]
   # listeners:
   #     - { 'event': 'response_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\contacts\models\ContactTypeModel'}
    defaults:
        component: components\companies\CompaniesComponent
        controller: components\companies\controllers\CompaniesController
        model: components\companies\models\CompanyModel
        method: save
        view: core\views\JSONView
        viewKey: admin_companies_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation' 
        