


admin_companies_home:
    pattern: admin/companies
    defaults:
        component: components\companies\CompaniesComponent
        controller: components\companies\controllers\CompaniesController
        model: components\companies\models\CompanyModel
        method: index
        view: extensions\angular\views\AngularTemplateView
        viewKey: admin_companies_home
        datasource: datasource1