
admin_companies_search1:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/companies/views/test.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
admin_companies_list:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "featureslider-edit": "src/components/companies/views/admin/edit.php"
            "featureslider": "src/components/companies/views/admin/view.php"
            "section3": "src/components/companies/views/admin/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_companies_edit:   
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/companies/views/admin/subnav.php"
            "section3": "src/components/companies/views/admin/edit.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
            
admin_propertymanagers_search:
    