


admin_companies_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "context-button": "src/components/companies/views/admin/context-button.php"
            "content": "src/components/companies/views/admin/list.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - companyAdmin
            - rootApp
    head:
        - @components/companies/dist/bower_components/angular/angular.min.js
        - @components/companies/dist/bower_components/jquery/dist/jquery.min.js
        - @components/companies/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/companies/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
    javascript:
        - @components/companies/dist/js/companies.concat.js
    css:
        - @components/companies/includes/css/companies.css
        
        


admin_companies_edit:
    template: admin-2cols.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "context-button": "src/components/companies/views/admin/context-button.php"
            "content": "src/components/companies/views/admin/edit.php"
            "sidecolumn": "src/components/companies/views/admin/edit-rightcol.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - companyAdmin
            - rootApp
    head:
        - @components/companies/dist/bower_components/angular/angular.min.js
        - @components/companies/dist/bower_components/jquery/dist/jquery.min.js
        - @components/companies/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/companies/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
    javascript:
        - @components/companies/dist/js/companies.concat.js
    css:
        - @components/companies/dist/css/company.min.css        