

admin_propertymanagers_search:
    
    

component_list:
    template: list.php
    sections: {"section1": "src/themes/default/templates/sections/header.php", "section2": "src/components/users/views/leftnav.php", "section3": "src/components/users/views/payload.php"}
    
users_list2:
    template: list.php
    sections: {"section1": "src/themes/default/templates/sections/header.php", "section2": "src/components/users/views/leftnav.php", "section3": "src/components/users/views/payload.php"}
 
admin_customers_company_edit: 
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/customers/views/admin/subnav.php"
            "section3": "src/components/customers/views/admin/add-company.php"
            "section4": "src/themes/default/templates/sections/footer.php"  

customers_list:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/customers/views/admin/subnav.php"
            "section3": "src/components/customers/views/admin/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
 
users_get:
    template: test.php
    sections: {"section1": "src/themes/default/templates/sections/header.php", "section2": "src/components/users/views/leftnav.php", "section3": "src/components/users/views/get.php"}
       
portal_login:
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section3": "src/components/customers/views/login/login-form.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
portal_login_submit:
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section3": "src/components/users/views/login/welcome.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
admin_customers_edit:  
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/customers/views/admin/subnav.php"
            "section3": "src/components/customers/views/admin/add.php"
            "section4": "src/themes/default/templates/sections/footer.php"  
            
admin_customers_save:       
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/customers/views/admin/subnav.php"
            "section3": "src/components/customers/views/admin/permissions.php"
            "section4": "src/themes/default/templates/sections/footer.php"     
            
admin_customers_permissions_get:    
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/customers/views/admin/subnav.php"
            "section3": "src/components/customers/views/admin/permissions.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
    
admin_customer_permissions_save:  
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/customers/views/admin/subnav.php"
            "section3": "src/components/customers/views/admin/save-success.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
    

admin_customers_credentials_get: 
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/customers/views/admin/subnav.php"
            "section3": "src/components/customers/views/admin/credentials.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
    
    
    #-------------------start portal area -----------------------
    
portal_customer_settings:  
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
           # "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/settings.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
    
customers_login_locked:   
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/locked.php"
            "section4": "src/themes/default/templates/sections/footer.php"  

customers_login_failed:  
    template: list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/login/failed.php"
            "section4": "src/themes/default/templates/sections/footer.php"       
            
portal_customers_edit: 
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/edit.php"
            "section4": "src/themes/default/templates/sections/footer.php"   
    
portal_customers_credentials_get:   
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            #"section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/credentials.php"
            "section4": "src/themes/default/templates/sections/footer.php"    
            
            
#---------------- invites ---------------------------            
portal_customers_list:     
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"    
            
portal_customer_invites_list:          
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/invites/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"      

            
portal_customer_invites_edit:          
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/invites/edit.php"
            "section4": "src/themes/default/templates/sections/footer.php"        
            
portal_customer_invites_login:
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/invites/login.php"
            "section4": "src/themes/default/templates/sections/footer.php"                
            
portal_customer_invites_login_submit:   
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            #"section2": "src/components/customers/views/invites/subnav.php"
            "section3": "src/components/customers/views/invites/welcome.php"
            "section4": "src/themes/default/templates/sections/footer.php"         
            
portal_customer_invites_invite:    
    template: portal-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/portal-header.php"
            "section2": "src/components/customers/views/subnav.php"
            "section3": "src/components/customers/views/invites/invite.php"
            "section4": "src/themes/default/templates/sections/footer.php"    
            
super_customers_roles_list:
    template: super-list.php
    sections: 
        -
            "section3": "src/components/customers/views/admin/roles/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"