

default_index:
    template: home.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/users/views/leftnav.php"
            "section3": "src/components/defaultItem/views/home.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    

default_about:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/about.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
   
default_contact:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/contact.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
        

default_collection:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/collection.php"
        - "section4": "src/themes/default/templates/sections/footer.php"        
        
admin_home:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/defaultItem/views/admin/home.php"
            "section4": "src/themes/default/templates/sections/footer.php"
          
    