

default_index:
    template: home.php
    sections: 
        -
            "section1": "themes/default/templates/sections/header.php"
            "section2": "components/users/views/leftnav.php"
            "section3": "components/defaultItem/views/home.php"
            "section4": "themes/default/templates/sections/footer.php"
    

default_about:
    template: home.php
    sections: {"section1": "themes/default/templates/sections/header.php", "section2": "components/users/views/leftnav.php", "section3": "components/defaultItem/views/payload.php"}

users_list2:
    template: list.php
    sections: {"section1": "themes/default/templates/sections/header.php", "section2": "components/users/views/leftnav.php", "section3": "components/users/views/payload.php"}
    