

default_index:
    template: home.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/header.php"
            "section2": "src/components/users/views/leftnav.php"
            "section3": "src/components/defaultItem/views/home.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    

default_about:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/about.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
        
default_about_glen:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/about-glen-meikle.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
   
default_wall_tablets:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/wall-tablets.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
   
default_design1:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/design.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
   
default_design2:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/design2.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
   
default_inspiration:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/inspiration.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
   
default_contact:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/contact.php"
        - "section4": "src/themes/default/templates/sections/footer.php"
        

default_collection:
    template: home.php
    sections: 
        - "section1": "src/themes/default/templates/sections/header.php"
        - "section2": "src/components/users/views/leftnav.php"
        - "section3": "src/components/defaultItem/views/content/collection.php"
        - "section4": "src/themes/default/templates/sections/footer.php"        