

projectaddress_autocomplete:
    
projectaddress_autocompletetest:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/staff/views/admin/subnav.php"
            "section3": "src/components/companies/views/test.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    