

#-------------------- inventory transfers ----------------

# super_inventory_equipment_transfer:
#     template: admin-list.php
#     sections:
#         -
#             "header": "src/themes/default/templates/sections/admin-header.php"
#             "content": "src/components/inventory/views/admin/equipment/transfer.php"
#             "footer": "src/themes/default/templates/sections/footer.php"




#-------------------- package types -----------------------
super_inventory_packagetypes_list:
    template: super-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/inventory/views/admin/packagetypes/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"

#-------------------- categories -----------------------
super_inventory_categories_list:
    template: super-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/inventory/views/admin/categories/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"

# ------------------- types -----------------------------

super_inventory_inventorytypes_list:
    template: super-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/inventory/views/admin/types/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"

#--------------------- Variants -----------------------

admin_inventory_variantoptions:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/inventory/views/admin/items/variant-options.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - inventoryAdmin
    head:
        - @components/claims/dist/bower_components/angular/angular.min.js
        - @components/claims/dist/bower_components/jquery/dist/jquery.min.js
        - @components/claims/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/claims/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/inventory/dist/js/inventory.concat.js
        #- @components/inventory/dist/js/claims.min.js
    css:
        - @components/inventory/dist/css/inventory.min.css

#--------------------- items --------------------------

admin_inventory_equipment_locations:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "content": "src/components/inventory/views/admin/equipment-locations/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - inventoryAdmin
    head:
        - @components/inventory/dist/bower_components/angular/angular.min.js
        - @components/inventory/dist/bower_components/jquery/dist/jquery.min.js
        - @components/inventory/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/inventory/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/inventory/dist/js/inventory.concat.js
        #- @components/inventory/dist/js/inventory.min.js
    css:
        - @components/inventory/dist/css/inventory.min.css


admin_inventory_materials_list:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/inventory/views/admin/items/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_inventory_items_list:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/inventory/views/admin/items/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_inventory_items_edit:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "content": "src/components/inventory/views/admin/items/edit.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - inventoryAdmin
    head:
        - @components/inventory/dist/bower_components/angular/angular.min.js
        - @components/inventory/dist/bower_components/jquery/dist/jquery.min.js
        - @components/inventory/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/inventory/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/inventory/dist/js/inventory.concat.js
        #- @components/inventory/dist/js/inventory.min.js
    css:
        - @components/inventory/dist/css/inventory.min.css

admin_inventory_list:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/inventory/views/admin/items/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - inventoryAdmin
    head:
        - @components/inventory/dist/bower_components/angular/angular.min.js
        - @components/inventory/dist/bower_components/jquery/dist/jquery.min.js
        - @components/inventory/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/inventory/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/inventory/dist/js/inventory.concat.js
        #- @components/inventory/dist/js/inventory.min.js
        - @components/claims/dist/js/claims.concat.js
        #- @components/claims/dist/js/claims.min.js
    css:
        - @components/inventory/dist/css/inventory.min.css

#------------------------- warehouse -----------------------

admin_warehouse_locations_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "content": "src/components/inventory/views/admin/warehouse/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - inventoryAdmin
    head:
        - @components/inventory/dist/bower_components/angular/angular.min.js
        - @components/inventory/dist/bower_components/jquery/dist/jquery.min.js
        - @components/inventory/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/inventory/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/inventory/dist/js/inventory.concat.js
        #- @components/inventory/dist/js/inventory.min.js
    css:
        - @components/inventory/dist/css/inventory.min.css
