<?php

return array(
    'section1' => 'Fú 福: Luck and Good fortune The character symbol “Fu” is popularly used in many decorative applications in art and architecture especially at entrances to bring constant good fortune. The fu character sometimes is displayed turned upside down because the meaning ‘to turn upside down’ =dao, is also a pun on the word arrived=dao and thus signifies (Good luck has arrived; Hǎo yùn dào le).',
    'section2' => 'Shòu 寿: Longevity
This is one of many varieties of characters symbolizing and represent the wishes for long life. ',
    'section3' => 'Shòu 寿 : Longevity This is one of many varieties of characters symbolizing that represent the wishes for long life. The beauty is its minimalism and meaning.',
    'section4' => 'Shuāng xǐ 喜喜 : Double Happiness The character for double happiness, often displayed during wedding celebrations, the colour red attracts jubilation and happiness, happiness is definitely doubled when it’s shared.',
    'section5' => 'Chinese elements of Decor-Lions head: 狮头: Shī tóu The lion\'s head (Shī tóu) has generally been used throughout history to denote power, bravery, strength and leadership. This is based on the idea of the lion being the recognized ruler of the animal kingdom. The Lion Head doorknockers are ancient guardians on doors for palaces, mansions and homes of royalties, officials and merchants. They’re said to prevent people of evil intentions from entering the house.',
    'section6' => 'Yún 云 = cloud: A Motif for Good Fortune The word for cloud: Yún 云sounds the same as in “Yun” in Yùnqì; meaning luck and so it’s a good fortune meaning. The cloud motif has many styles and is used in all kinds of decorative objects, clothing, furniture, and in architecture.',
    'section7' => '财Cái :The symbol for Wealth Traditionally, Chinese cash coins were cast in copper, brass or iron. The round shape signifies heaven and the square shape earth. Ancient coins became a symbol of wealth and prosperity. Inscribed on this coin is “Gōngxǐ fā cái” literally meaning blessings to deliver wealth. Two coins hung above a business’s door represent the God of Wealth and attract wealth to business. 恭 (gōng) : respectful, polite, reverent, blessing / 喜 (xǐ) : like, love, enjoy; joyful thing / 发 (fā) : issue, dispatch, send out / 財, 财 (cái) : wealth, valuables, riches ',
    'section8' => 'Jiǔ 九=Nine: Longevity (Jiǔ 九=nine) the number nine represents longevity as the word Jiǔ is a pun on the word forever. The doors at the forbidden city have large door nail rivets 9 across and nine down; the #9 was a favourite number of many emperors as 9 was the largest number digit and whenever 9 is multiplied with any number the sum is always 9, 9x9=81 (8+1=9); 81+81=162 (1+6+2=9) ;(9x6=54) 5+4=9;The number nine is often integrated in amounts in imperial structures and designs. ',
    'section9' => 'Yún 云 = cloud: A Motif for Good Fortune The word for cloud: Yún 云sounds the same as in “Yun” in Yùnqì; meaning luck and so it’s a good fortune meaning. The cloud motif has many styles and is used in all kinds of decorative objects, clothing, furniture, and in architecture. ',
    'section10' => 'Three gold ingots=Symbol of prosperity: Lù 禄 Yuánbǎo is the name for money in the form of a hat shape in Ancient China and is also a symbol of wealth, status and honour. During imperial examinations the scholars whom passed with highest marks were referred to as Hui Yuan, Jie Yuan, and Zhuang Yuan, together as the three Yuan’s. The yuanbao were owned in historic times by high ranking officials, emperors, and tycoons only.',
    'section11' => 'Silver ingot: Symbol for Wealth: 财 Cái
Yuánbǎo – meaning original treasure has been used as currency in many dynasties. Used as a type of currency in silver or gold in China until the 20th century; where the Yuan dynasty standardized the currency and were then made of silver. The ingots were made by individual silversmiths for local exchange; as a result, the shape and amount of extra detail on each ingot were highly variable.',
    'section12' => 'Phoenix凤凰: Symbolic for Double Happiness The phoenix pronounced in mandarin is Fènghuáng; It is believed that phoenix only appear in areas or places that are blessed with utmost peace and prosperity or happiness. The phoenix represented power sent from the heavens to the Empress. If a phoenix was used to decorate a house it symbolized that loyalty and honesty were in the people that lived there.',
    'section13' => 'Fret Motif=Represents Wealth: 财 Cái Is a decorative border usually a continuous border and a symbol of endless wealth: Cái. The fret is often incorporated on furniture, textiles, and porcelain decoration.',
    'section14' => 'Biānfú =Motif for Luck The word biānfú (蝙蝠); meaning Bat in Chinese, contains the word “Fu” which sounds the same as the Chinese word Fú 福 that means “good fortune, blessing, and happiness.” Therefore, the bat motif symbolizes good luck. The bat motif is often used with the longevity character as is here. ',
    'section15' => 'Peony-Motif for Prosperity: Lù 禄
Peony in Chinese is pronounced mǔdān 牡丹 and is a symbol of prosperity and nobility. Known as the ‘king of the flowers’, the peony is a symbol of royalty and virtue. It is also called the ‘flower of wealth and honour’ (fuguihua 富貴花) and is widely used to represent wealth and honour. The peony also represents spring while symbolized expresses and articulates female beauty.',
    'section16' => 'Peony-Motif for Prosperity: Lù 禄 Peony in Chinese is pronounced mǔdān 牡丹 and is a symbol of prosperity and nobility. Known as the ‘king of the flowers’, the peony is a symbol of royalty and virtue. It is also called the ‘flower of wealth and honour’ (fuguihua 富貴花) and is widely used to represent wealth and honour. The peony also represents spring while symbolized expresses and articulates female beauty.',
    'section17' => 'Lotus:Liánhuā 莲花: Motif for Double Happiness The lotus is the flower of the sixth month and summer. It is a symbol of purity because it rises out of the mud to bloom, thus also representing female virtues. The Lotus blossoms are often depicted as a throne for the Buddha, and used with other motifs; reflect continued luck and wealth. The Lotus also symbolizes an ideal personality in Chinese culture. Here it is bordered with a cloud motif. ',
    'section18' => 'Clematis flower and vine – An element of an Oriental design motif; although beholding intricacies and repetitiveness the design is graceful with simple beauty. ',
    'section19' => 'Crane= Hè 鹤: Motif for Longevity The crane is a symbol of longevity because it has a long life span and its white feathers stand for old age. It also represents high status as the crane is regarded as ‘a bird of the first rank’ in the imperial hierarchy. Flying cranes symbolise a wish or hope to become a representative in a higher respected position.',
    'section20' => 'Lotus:Liánhuā 莲花: Motif for Double Happiness The lotus is the flower of the sixth month and summer. It is a symbol of purity because it rises out of the mud to bloom, thus also representing female virtues. The Lotus blossoms are often depicted as a throne for the Buddha, and used with other motifs; reflect continued luck and wealth. The Lotus also symbolizes an ideal personality in Chinese culture. ',
    'section21' => 'Shòu 寿 : Longevity This is one of many varieties of characters symbolizing the wishes for long life. Set amongst colourful vigorous vines',
    'section22' => 'Chrysanthemum: Motif for Longevity: Shòu 寿 The pronunciation of this flower is Júhuā and “Jú” is similar to “jiǔ” meaning forever; and thus symbolizing longevity. The center of the flower also has one of many varieties of characters that represent the wishes for long life.',
    'section23' => 'Lotus:Liánhuā 莲花: Motif for Double Happiness The lotus is the flower of the sixth month and summer. It is a symbol of purity because it rises out of the mud to bloom, thus also representing female virtues. The Lotus blossoms are often depicted as a throne for the Buddha, and used with other motifs; reflect continued luck and wealth. The Lotus also symbolizes an ideal personality in Chinese culture. ',
    'section24' => 'Lotus:Liánhuā 莲花: Motif for Double Happiness The lotus is the flower of the sixth month and summer. It is a symbol of purity because it rises out of the mud to bloom, thus also representing female virtues. The Lotus blossoms are often depicted as a throne for the Buddha, and used with other motifs; reflect continued luck and wealth. The Lotus also symbolizes an ideal personality in Chinese culture. ',
    'section25' => 'Eight = (ba 八):Represents wealth: 财 Cái Ba 八 for ‘eight’ is pronounced similarly to fa 发 for ‘to expand’, as in ‘to expand in wealth’ (facai发财). Due to this connection, people like to include the number eight in items such as telephone numbers, street addresses and car registration plates as they believe it will bring good fortune. Here there is eight of each type of eights ',
    'section26' => 'Yún 云 = cloud: A Motif for Good Fortune The word for cloud: Yún 云sounds the same as in “Yun” in Yùnqì; meaning luck and so it’s a good fortune meaning. The cloud motif has many styles and is used in all kinds of decorative objects, clothing, furniture, and in architecture.',
    'section27' => 'Dragon (Long龙): Motif for Luck and Good fortune The Chinese dragon is the ultimate and the most powerful symbol of protection and good fortune. Ranked first among mythical beasts; it can bring rain to parched lands and provide good harvests, which in turn represents abundance and relief thus worshipped by the common people. A dragon and phoenix (king of all winged creatures) symbolise the emperor and empress as well as marital bliss. The dragon is often used as an emblem of high rank and power on the robes of emperors and princes as well as on imperial art objects. ',
    'section28' => 'Lotus:Liánhuā 莲花: Motif for Double Happiness The lotus is the flower of the sixth month and summer. It is a symbol of purity because it rises out of the mud to bloom, thus also representing female virtues. The Lotus blossoms are often depicted as a throne for the Buddha, and used with other motifs; reflect continued luck and wealth. The Lotus also symbolizes an ideal personality in Chinese culture.',
    'section29' => 'Plum Blossom: Méihuā 梅花 = Motif for Longevity:Shòu 寿
The plum blossom has extensively been held in high admiration for its beauty; also its one of the few flowers that blossoms in the cold of winter thus represents longevity. The plum blossom is often used as a delicate accent motif in textile patterns. ',
    'section30' => 'Plum Blossom and Bamboo: Motif for Double Happiness: Shuāng xǐ 喜喜 Plum blossom (Méihuā 梅花) on its own represents longevity but paired with bamboo (Zhúzi竹子) create a wish for double happiness. The five petals of the plum blossom are auspicious since the number five is sacred in China and the bamboo represents strength. The combination is often given as a wedding gift. '
);

