<?php

return array(
    'section1' => 'The culmination of his experiences and influences in China can be found in Glen’s creation, what he calls "Good Fortune no.88 Tablets". This wall decor was inspired to symbolize the concepts in auspicious meanings, good wishes and fortune reflecting his immersion into the Chinese culture. The construction of the tablets measure 8 inches by 8 inches because the number "8" is an auspicious number in China. Keeping with this theme, the tablets are approximately 2 inches thick representing the double in "Double Happiness". The surrounding border is reflective of many Chinese ornate, graphical screen designs and other Chinese border details. They are formed to look like cast black iron and aged pitted metal. The tablets are all hand poured plaster and painted one at a time, they may be similar looking but no two are exactly alike; making each piece unique. There are multiple processes and techniques among which are painting, sculpting, and molding to achieve the antique aged look, reflective of Old China past. The intention is to capture and reflect both elements of Oriental design and Chinese auspicious meanings: ',
    'section2' => 'Fu = Good Fortune; Lu = Prosperity; Shou = Longevity; Xi = Double Happiness; Cai =Wealth. ',
    'section3' => 'Glen’s journey of discovery of the Chinese culture continues to unfold and though he has described respective meaning or a specific design element on the back of the tablets; it conversely is concise and encourages everyone to explore more about their respective meaning where associated. The Chinese symbolism consists of rich signs with collective meanings and can vary from region to region in China. The entire collection of designs can visually make your surroundings unique by your personal selections and how they are arranged and displayed. He hopes this opens up the mystical world of Chinese Culture while surrounding your interior with auspicious meaning and beautiful design of Chinese splendor.',
    'section4' => 'Oxford University Press Thesaurus: Auspicious - Favourable, Promising, Positive, Fortunate, Propitious, Lucky, and Good ',
    'section5' => 'Around 6 or so years ago, I wanted to decorate my office with something that conveyed a good meaning and reflected the unique elements of Chinese design. A few American colleagues who I worked with noticed the tablets and asked, "Where did these come from?" My immediate response without much thought was, "Oh, at some store in Hong Kong....why?" Intrigued, they replied, "Because they’re really cool and I wouldn’t mind buying them for my home ….they are really beautiful". I continued, "well…I can get them for you". They went on asking, "Do you know the shop owner?" My response was a coy, "as a matter of fact I do….me…I actually sculpted and painted them myself". They replied "Really?...Really!…I knew you could make a lot of things but didn’t know you sculpted like that too!?!"',
    'section6' => 'The memory of that simple encounter still makes me smile today. My Asian colleagues and friends have been equally inquisitive of the origins of the tablets already knowing many of their symbolism and meanings. Since that time I have had numerous friends, over the years, encourage me to pursue this passion. As with so many artists the process and evolution of design concepts in one’s head must evolve organically....nothing can be forced. Only until now, have I immersed myself into following one of my passions completely and unabated. I have never had so much joy in creating...…well actually I have always had joy just maybe not this much fun.....making these in my studio, listening to music and creating beautiful, unique pieces of art....I just wish I would have started earlier. I hope they give you as much pleasure and warm-hearted meaning as I enjoy making them! "Zhende!" That’s the Mandarin pinyin spelling for "Really!" '
);
