
default:
    htmltags:
        container: blog
        tags:            
            title: @metaTitle
            description: @metaDescription
            type: blog  
    
    
website_blogs_list: 
    htmltags:
        container: Blogs
        tags:            
                title: 'Restoration Services | Flood Fire Smoke Advice'
                description: @metaDescription
                type: blog