compression_css:
    pattern: compression/css/*
    defaults:
        component: core\components\compression\CompressionComponent
        controller:  core\components\compression\controllers\CompressionController
        model:  core\components\compression\models\CompressionModel
        method: sendFile
        view: core\components\compression\views\ResourceFileView
        viewKey: compression_css
        datasource: datasource1             
        
compression_js:
    pattern: compression/js
    defaults:
        component: core\components\compression\CompressionComponent
        controller:  core\components\compression\controllers\CompressionController
        model:  core\components\compression\models\CompressionModel
        method: sendFile
        view: core\components\compression\views\ResourceFileView
        cachedView: core\components\compression\views\ResourceFileView
        viewKey: compression_js
        datasource: datasource1   
    listeners:
        - { 'event': 'entry_point', 'listener': 'core\components\compression\listeners\LoadConcatenatedFileFromCacheListener', responseKey: CACHED_PAGE_ON_ENTRY_POINT }
        - { 'event': 'render_complete', 'listener': 'core\components\compression\listeners\SaveConcatenatedFileToCacheListener' }
            