

admin_messaging_send:
    listeners:
         - { 'class': 'components\inventory\models\WarehouseModel', 'event': 'save_success', 'listener': 'components\messaging\listeners\SendInAppMessageListener', 'datasource': 'java_proxy' }