
#------------------- new layout items --------------

admin_messaging_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "notifications": "/src/themes/default/templates/sections/notification-area.php"
            leftnav: src/themes/default/templates/sections/left-nav.php
            "content": src/components/messaging/views/admin/messages/list.php
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
           # - messagingAdmin

    head:
        - @components/claims/dist/bower_components/angular/angular.min.js
        - @components/claims/dist/bower_components/jquery/dist/jquery.min.js
        - @components/claims/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/claims/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        - @extensions/angular/dist/bower_components/dropzone/dist/min/dropzone.min.js

    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        #- @extensions/angular/dist/js/angular-extension.min.js
        - @components/messaging/dist/js/messaging.concat.js

        #- @components/staff/dist/js/staff.min.js
    css:
        - @components/messaging/dist/css/messaging.min.css
        - @extensions/angular/dist/bower_components/dropzone/dist/dropzone.css


            
 
admin_messaging_view_selected:                
    template: admin-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            #"section3": "src/components/messaging/views/templates/add.php"
            "footer": "src/themes/default/templates/sections/footer.php"    
            
admin_messaging_compose:    
    template: admin-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            #"section3": "src/components/messaging/views/templates/add.php"
            "footer": "src/themes/default/templates/sections/footer.php"              

#------------------ legacy layout items -----------

admin_messaging_list:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/messaging/views/admin/subnav.php"
            "section3": "src/components/messaging/views/admin/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
    
admin_messaging_create:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/messaging/views/admin/subnav.php"
            "section3": "src/components/messaging/views/admin/add.php"
            "section4": "src/themes/default/templates/sections/footer.php"    
    
admin_messaging_save:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/messaging/views/admin/subnav.php"
            "section3": "src/components/messaging/views/admin/sent.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
            
admin_messaging_claim_list:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/messaging/views/admin/subnav.php"
            "section3": "src/components/messaging/views/admin/list.php"
            "section4": "src/themes/default/templates/sections/footer.php" 
    
admin_messaging_templates_list:   
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/messaging/views/admin/subnav.php"
            "section3": "src/components/messaging/views/templates/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"  
            
admin_messaging_templates_edit:         
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/messaging/views/admin/subnav.php"
            "section3": "src/components/messaging/views/templates/add.php"
            "section4": "src/themes/default/templates/sections/footer.php"     
            
       