


messaging_list_all: 'src/components/messaging/views/widgets/list.php'

messaging_folders: 'src/components/messaging/views/widgets/folders.php'

messaging_view_selected: 'src/components/messaging/views/widgets/view.php'

messaging_compose: 'src/components/messaging/views/widgets/compose.php'