callmatrix_list_by_date:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/callmatrix/views/admin/subnav.php"
            "section3": "src/components/callmatrix/views/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"

callmatrix_calendar:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/callmatrix/views/admin/subnav.php"
            "section3": "src/components/callmatrix/views/calendar.php"
            "section4": "src/themes/default/templates/sections/footer.php"

callmatrix_calendar_add_staff:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/callmatrix/views/admin/subnav.php"
            "section3": "src/components/callmatrix/views/addStaff.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    