

admin_workperformed_list:
    pattern: admin/workperformed/*/*
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\departments\models\DepartmentModel', 'cacheKey': 'Departments' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimPhaseModel', 'cacheKey': 'ClaimPhases' }
    defaults:
        component: components\workperformed\WorkPerformedComponent
        controller: components\workperformed\controllers\WorkPerformedController
        model: components\workperformed\models\WorkPerformedModel
        method: listall
        view: core\views\TemplateView
        viewKey: admin_workperformed_list
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'
            
admin_workperformed_edit:
    pattern: admin/workperformed/*
    methods: [GET]
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\departments\models\DepartmentModel', 'cacheKey': 'Departments' }
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\claims\models\ClaimPhaseModel', 'cacheKey': 'ClaimPhases' }
    defaults:
        component: components\workperformed\WorkPerformedComponent
        controller: components\workperformed\controllers\WorkPerformedController
        model: components\workperformed\models\WorkPerformedModel
        method: edit
        view: core\views\TemplateView
        viewKey: admin_workperformed_edit
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'    
            
admin_workperformed_save:
    pattern: admin/workperformed/*
    methods: [POST]
    listeners:
        - { 'event': 'request_start', 'listener': 'components\validation\listeners\ValidateNestedFormListener' }
    defaults:
        component: components\workperformed\WorkPerformedComponent
        controller: components\workperformed\controllers\WorkPerformedController
        model: components\workperformed\models\WorkPerformedModel
        method: save
        view: core\views\TemplateView
        viewKey: admin_workperformed_save
        datasource: datasource1
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Navigation'            