admin_documents_upload:
    listeners:
        - { 'cacheKey': 'DocumentFiles', 'class': 'components\claims\models\ClaimDocumentModel', 'event': 'request_start', 'listener': 'components\documents\listeners\UploadDocumentsListener', 'datasource': 'datasource1' }
