admin_documents_list:
    listeners:
        # - { 'cacheKey': 'LocationFiles', 'class': 'components\documents\models\DocumentModel', 'event': 'request_start', 'listener': 'components\claims\listeners\LoadFileCountsListener', 'datasource': 'datasource1' }
