

super_documents_list:
    pattern: super/documents/*/*
    defaults:
        component: components\documents\DocumentsComponent
        controller: components\documents\controllers\DocumentsController
        model: components\documents\models\DocumentModel
        method: listall
        view: core\views\TemplateView
        viewKey: super_documents_list
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  
    methods: [GET]

     

super_documents_edit:
    pattern: super/documents/*
    defaults:
        component: components\documents\DocumentsComponent
        controller: components\documents\controllers\DocumentsController
        model: components\documents\models\DocumentModel
        method: edit
        view: core\views\TemplateView
        viewKey: super_documents_edit
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  
    methods: [GET]     
     
super_documents_save:
    pattern: super/documents/*
    defaults:
        component: components\documents\DocumentsComponent
        controller: components\documents\controllers\DocumentsController
        model: components\documents\models\DocumentModel
        method: save
        view: core\views\JSONView
        viewKey: super_documents_save
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  
    methods: [POST] 
    
super_documents_remove:
    pattern: super/documents/remove/*
    defaults:
        component: components\documents\DocumentsComponent
        controller: components\documents\controllers\DocumentsController
        model: components\documents\models\DocumentModel
        method: setInactive
        view: core\views\JSONView
        viewKey: super_documents_save
        datasource: datasource1
        langFiles: 
            - 'src/components/defaultItem/locales/*/Navigation'  
    methods: [POST]     
    