


cssmenu_ceilingbar:    
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/cssmenu/views/ceilingbar.php"     
            
cssmenu_superuserbar:   
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/cssmenu/views/ceilingbar-superuser.php"         
            
cssmenu_adminbar:  
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/cssmenu/views/ceilingbar-admin.php"            
            
cssmenu_pancakes:   
    template: newsfeed.php
    sections: 
        -
            "section1": "src/components/cssmenu/views/verticalmenu-admin.php"       