

admin_contents_list:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/contents/views/admin/subnav.php"
            "section3": "src/components/contents/views/admin/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
admin_contents_job_list:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/contents/views/admin/subnav.php"
            "section3": "src/components/contents/views/admin/joblist.php"
            "section4": "src/themes/default/templates/sections/footer.php"

admin_contents_job_edit:
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/contents/views/admin/subnav.php"
            "section3": "src/components/contents/views/admin/add.php"
            "section4": "src/themes/default/templates/sections/footer.php"
            
            
admin_contents_packages_edit:  
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/contents/views/admin/subnav.php"
            "section3": "src/components/contents/views/admin/packages/add.php"
            "section4": "src/themes/default/templates/sections/footer.php"     
            
    
admin_contents_package_items_list:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/contents/views/admin/subnav.php"
            "section3": "src/components/contents/views/admin/packages/items-list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    

admin_contents_schedules_list:     
    template: admin-list-fullscreen.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/scheduling/views/subnav.php"
            "section3": "src/components/scheduling/views/grid-compressed.php"
            "section4": "src/themes/default/templates/sections/footer.php"    