
super_widgetpages_home:
    pattern: super/widgets/pages
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetPagesController
        model:  core\components\widgets\models\WidgetPageModel
        method: index
        view: core\views\TemplateView
        viewKey: super_widgetpages_home
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]


super_widgetpages_list_templates:
    pattern: super/widgets/pages/list
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetPagesController
        model:  core\components\widgets\models\WidgetPageModel
        method: listTemplates
        view: core\views\JSONView
        viewKey: super_widgetpages_get
        datasource: datasource1
    listeners:
        - { 'event': 'request_start', 'cacheKey': 'PageTemplates', 'listener': 'core\components\widgets\eventlisteners\LoadWidgetPageTemplateListener', 'datasource': 'datasource1'}

    methods: [GET]


super_widgetpages_list:
    pattern: super/widgets/pages/*/*
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetPagesController
        model:  core\components\widgets\models\WidgetPageModel
        method: listall
        view: core\views\JSONView
        viewKey: super_widgetpages_list
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]

super_widgetpages_get:
    pattern: super/widgets/pages/*
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetPagesController
        model:  core\components\widgets\models\WidgetPageModel
        method: edit
        view: core\views\JSONView
        viewKey: super_widgetpages_get
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]

super_widgetpages_save:
    pattern: super/widgets/pages/*
    listeners:
        - { 'event': 'save_success', 'listener': 'core\components\widgets\eventlisteners\DeleteCachedPagesListener', 'datasource': 'datasource1'}
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetPagesController
        model:  core\components\widgets\models\WidgetPageModel
        method: savePageWidgets
        view: core\views\JSONView
        viewKey: super_widgetpages_save
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [POST]



super_widgets_list_unassigned_all:
    pattern: super/widgets/unassigned/all/*
    listeners:
        - { 'event': 'request_start', addToResponse: false, 'listener': 'core\components\widgets\eventlisteners\LoadUnassignedWidgetsListener', 'datasource': 'datasource1'}
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsController
        model:  core\components\widgets\models\WidgetModel
        method: listallUnassigned
        view: core\views\JSONView
        viewKey: super_widgets_list_unassigned_all
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]



super_widgets_list_unassigned:
    pattern: super/widgets/unassigned/*/*/*
    listeners:
        - { 'event': 'request_start', addToResponse: false, 'listener': 'core\components\widgets\eventlisteners\LoadUnassignedWidgetsListener', 'datasource': 'datasource1'}
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsController
        model:  core\components\widgets\models\WidgetModel
        method: listallUnassignedPaginated
        view: core\views\JSONView
        viewKey: super_widgets_list_unassigned
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]



super_widgetpages_widgets_list:
    pattern: super/widgets/pages/widgets/*
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetPageWidgetsController
        model:  core\components\widgets\models\WidgetPageWidgetModel
        method: listallByPage
        view: core\views\JSONView
        viewKey: super_widgetpages_save
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]


super_widgets_home:
    pattern: super/widgets
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsController
        model:  core\components\widgets\models\SystemWidgetModel
        method: index
        view: core\views\TemplateView
        viewKey: super_widgets_home
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]


super_widgets_system_home:
    pattern: super/widgets/system
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsSystemController
        model:  core\components\widgets\models\SystemWidgetModel
        method: index
        view: core\views\TemplateView
        viewKey: super_widgets_system_home
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]

super_widgets_list:
    pattern: super/widgets/*/*
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsController
        model:  core\components\widgets\models\WidgetModel
        method: listall
        view: core\views\JSONView
        viewKey: super_widgets_list
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [GET]



super_widgets_save:
    pattern: super/widgets/*
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsController
        model:  core\components\widgets\models\WidgetModel
        method: save
        view: core\views\JSONView
        viewKey: super_widgets_save
        datasource: datasource1
        langFiles:
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'
    methods: [POST]
