

     
super_widgets_home:
    pattern: super/widgets
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsController
        model:  core\components\widgets\models\SystemWidgetModel
        method: index
        view: core\views\TemplateView
        viewKey: super_widgets_home
        datasource: datasource1  
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'    
    methods: [GET]

     
super_widgets_list:
    pattern: super/widgets/*/*
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsController
        model:  core\components\widgets\models\WidgetModel
        method: listall
        view: core\views\JSONView
        viewKey: super_widgets_list
        datasource: datasource1  
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'    
    methods: [GET]    
    

     
super_widgets_save:
    pattern: super/widgets/*
    defaults:
        component: core\components\widgets\WidgetsComponent
        controller:  core\components\widgets\controllers\WidgetsController
        model:  core\components\widgets\models\WidgetModel
        method: save
        view: core\views\JSONView
        viewKey: super_widgets_save
        datasource: datasource1  
        langFiles: 
            - 'src/framework/core/components/locales/resources/*/Locales'
            - 'src/components/shoppingcart/locales/*/Navigation'    
    methods: [POST]       