


super_widgets_home:
    template: super-list.php
    sections: 
        -
            "section1": "src/components/shoppingcart/views/admin/topnav.php"
            "section3": "src/framework/core/components/widgets/views/super/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    