


accounting_timesheets_home:
    template: admin-list.php
    sections:
        - 
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/accounting/views/timesheets/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - accountingAdmin
    head:
        - @components/accounting/dist/bower_components/angular/angular.min.js
        - @components/accounting/dist/bower_components/jquery/dist/jquery.min.js
        - @components/accounting/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/accounting/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        #- @extensions/angular/ng/js/phoenixSearchSrv.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        - @components/accounting/dist/js/accounting.concat.js
    css:
        - @components/accounting/dist/css/accounting.min.css

accounting_generalcosts_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/accounting/views/generalcosts/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - accountingAdmin
    head:
        - @components/accounting/dist/bower_components/angular/angular.min.js
        - @components/accounting/dist/bower_components/jquery/dist/jquery.min.js
        - @components/accounting/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/accounting/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        - @components/accounting/dist/js/accounting.concat.js
    css:
        - @components/accounting/dist/css/accounting.min.css


accounting_pos_list:
    template: admin-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "section2": "src/components/accounting/views/admin/subnav.php"
            "section3": "src/components/accounting/views/admin/parameters.php"
            "footer": "src/themes/default/templates/sections/footer.php"

accounting_costcarditemtypes_home:
    template: super-list.php
    sections:
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section3": "src/components/accounting/views/costCardItemTypes/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - accountingAdmin


accounting_tabs_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/accounting/views/tabstest/tabs.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - accountingAdmin
            - staffAdmin
            - claimsAdmin
    head:
        - @components/accounting/dist/bower_components/angular/angular.min.js
        - @components/accounting/dist/bower_components/jquery/dist/jquery.min.js
        - @components/accounting/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/accounting/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        #- @extensions/angular/ng/js/phoenixSearchSrv.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        - @components/accounting/dist/js/accounting.concat.js
        - @components/staff/dist/js/staff.concat.js
        - @components/claims/dist/js/claims.concat.js
        - @components/claims/includes/js/jquery.ptTimeSelect.js
    css:
        - @components/accounting/dist/css/accounting.min.css
        - @components/staff/dist/css/staff.min.css
        - @components/claims/dist/css/claims.min.css
        - @components/claims/includes/css/jquery.ptTimeSelect.css