admin_projects_search:
    pattern: admin/projects/search
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: search
        view: core\views\JSONView
        viewKey: admin_projects_search
        datasource: datasource1

admin_projects_home:
    pattern: admin/projects
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: index
        view: extensions\angular\views\AngularTemplateView
        viewKey: admin_projects_home
        datasource: datasource1
        langFiles:
            -  'app/locales/*/website' 
            -  'src/components/projects/locales/*/Project' 

admin_projects_get:
    pattern: admin/projects/*
    listeners:
    #    - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: get
        view: core\views\JSONView
        viewKey: admin_projects_get
        datasource: datasource1  
    methods: [GET]   

admin_projects_save:
    pattern: admin/projects/*
    listeners:
    #    - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: save
        view: core\views\JSONView
        viewKey: admin_projects_save
        datasource: datasource1  
    methods: [POST]       

admin_projects_edit:
    pattern: admin/projects/edit/*
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: edit
        view: extensions\angular\views\AngularTemplateView
        viewKey: admin_projects_edit
        datasource: datasource1  
        langFiles:
            -  'src/components/projects/locales/*/Project' 
        

admin_projects_list:
    pattern: admin/projects/*/*
    listeners:
    #    - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: listall
        view: core\views\JSONView
        viewKey: admin_projects_list
        datasource: datasource1         