projectaddress_autocomplete:
    pattern: admin/projects/addresses/search
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: search
        view: core\views\JSONView
        viewKey: projectaddress_autocomplete
        datasource: datasource1
        
floorplans_list:
    pattern: admin/projects/floorplans/*
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectFloorPlansController
        model: components\projects\models\FloorPlanModel
        method: listall
        view: core\views\TemplateView
        viewKey: floorplans_list
        datasource: datasource1
    methods: [GET]        
        
projectaddress_edit:
    pattern: admin/projects/*
    listeners:
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: edit
        view: core\views\TemplateView
        viewKey: projectaddress_edit
        datasource: datasource1
    methods: [GET]
        
         
projectaddress_save:
    pattern: admin/projects/*
    listeners:
        - { 'event': 'entry_point', 'listener': 'components\validation\listeners\ValidateNestedFormListener'}  
        - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: save
        view: core\views\TemplateView
        viewKey: projectaddress_save
        datasource: datasource1
    methods: [POST]
               
  
        
projectaddress_list:
    pattern: admin/projects/*/*
    defaults:
        component: components\projects\ProjectsComponent
        controller: components\projects\controllers\ProjectAddressesController
        model: components\projects\models\ProjectAddressModel
        method: listall
        view: core\views\TemplateView
        viewKey: projectaddress_list
        datasource: datasource1      
                