

    
admin_projects_home:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/projects/views/admin/addresses/list.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - projectAddressesAdmin
    head:
        - @components/projects/dist/bower_components/angular/angular.min.js
        - @components/projects/dist/bower_components/jquery/dist/jquery.min.js
        - @components/projects/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/projects/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        #- @extensions/angular/ng/js/phoenixSearchSrv.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        - @components/projects/dist/js/projects.concat.js
    css:
        - @components/projects/dist/css/projects.min.css


admin_projects_edit:
    template: admin-list.php
    sections:
        -
            "header": "src/themes/default/templates/sections/admin-header.php"
            "leftnav": "src/themes/default/templates/sections/left-nav.php"
            "content": "src/components/projects/views/admin/addresses/edit.php"
            "footer": "src/themes/default/templates/sections/footer.php"
    angular:
        bootstrap_modules:
            - rootApp
            - projectAddressesAdmin
            #- claimsAdmin
    head:
        - @components/projects/dist/bower_components/angular/angular.min.js
        - @components/projects/dist/bower_components/jquery/dist/jquery.min.js
        - @components/projects/dist/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js
        - @components/projects/dist/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
        #- @extensions/angular/ng/js/phoenixSearchSrv.js
    javascript:
        - @extensions/angular/dist/js/angular-extension.concat.js
        - @components/projects/dist/js/projects.concat.js
    css:
        - @components/projects/dist/css/projects.min.css