

projectaddress_autocomplete:
    
projectaddress_autocompletetest:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/projects/views/admin/subnav.php"
            "section3": "src/components/companies/views/test.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
projectaddress_edit:
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/projects/views/admin/subnav.php"
            "section3": "src/components/projects/views/admin/address.php"
            "section4": "src/themes/default/templates/sections/footer.php"
    
    
projectaddress_list:  
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/projects/views/admin/subnav.php"
            "section3": "src/components/projects/views/admin/list-addresses.php"
            "section4": "src/themes/default/templates/sections/footer.php"  
            
floorplans_edit:  
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/projects/views/admin/subnav.php"
            "section3": "src/components/projects/views/admin/floorplans/edit.php"
            "section4": "src/themes/default/templates/sections/footer.php"  
            
floorplans_list:    
    template: admin-list.php
    sections: 
        -
            "section1": "src/themes/default/templates/sections/admin-header.php"
            "section2": "src/components/projects/views/admin/subnav.php"
            "section3": "src/components/projects/views/admin/floorplans/list.php"
            "section4": "src/themes/default/templates/sections/footer.php"          
    

